package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * DeviceGeofence generated by hbm2java
 */
public class DeviceGeofence implements java.io.Serializable {

	private DeviceGeofenceId id;
	private Devices devices;
	private Geofences geofences;

	public DeviceGeofence() {
	}

	public DeviceGeofence(DeviceGeofenceId id, Devices devices, Geofences geofences) {
		this.id = id;
		this.devices = devices;
		this.geofences = geofences;
	}

	public DeviceGeofenceId getId() {
		return this.id;
	}

	public void setId(DeviceGeofenceId id) {
		this.id = id;
	}

	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	public Geofences getGeofences() {
		return this.geofences;
	}

	public void setGeofences(Geofences geofences) {
		this.geofences = geofences;
	}

}
