package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Devices generated by hbm2java
 */
public class Devices implements java.io.Serializable {

	private int id;
	private Groups groups;
	private String name;
	private String uniqueid;
	private Date lastupdate;
	private Integer positionid;
	private String attributes;
	private Set<UserDevice> userDevices = new HashSet<UserDevice>(0);
	private Set<DeviceGeofence> deviceGeofences = new HashSet<DeviceGeofence>(0);
	private Set<AttributeAliases> attributeAliaseses = new HashSet<AttributeAliases>(0);
	private Set<Events> eventses = new HashSet<Events>(0);
	private Set<Positions> positionses = new HashSet<Positions>(0);

	public Devices() {
	}

	public Devices(int id, String name, String uniqueid) {
		this.id = id;
		this.name = name;
		this.uniqueid = uniqueid;
	}

	public Devices(int id, Groups groups, String name, String uniqueid, Date lastupdate, Integer positionid,
			String attributes, Set<UserDevice> userDevices, Set<DeviceGeofence> deviceGeofences,
			Set<AttributeAliases> attributeAliaseses, Set<Events> eventses, Set<Positions> positionses) {
		this.id = id;
		this.groups = groups;
		this.name = name;
		this.uniqueid = uniqueid;
		this.lastupdate = lastupdate;
		this.positionid = positionid;
		this.attributes = attributes;
		this.userDevices = userDevices;
		this.deviceGeofences = deviceGeofences;
		this.attributeAliaseses = attributeAliaseses;
		this.eventses = eventses;
		this.positionses = positionses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Integer getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Integer positionid) {
		this.positionid = positionid;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public Set<UserDevice> getUserDevices() {
		return this.userDevices;
	}

	public void setUserDevices(Set<UserDevice> userDevices) {
		this.userDevices = userDevices;
	}

	public Set<DeviceGeofence> getDeviceGeofences() {
		return this.deviceGeofences;
	}

	public void setDeviceGeofences(Set<DeviceGeofence> deviceGeofences) {
		this.deviceGeofences = deviceGeofences;
	}

	public Set<AttributeAliases> getAttributeAliaseses() {
		return this.attributeAliaseses;
	}

	public void setAttributeAliaseses(Set<AttributeAliases> attributeAliaseses) {
		this.attributeAliaseses = attributeAliaseses;
	}

	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

	public Set<Positions> getPositionses() {
		return this.positionses;
	}

	public void setPositionses(Set<Positions> positionses) {
		this.positionses = positionses;
	}

}
