package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * DeviceGeofenceId generated by hbm2java
 */
public class DeviceGeofenceId implements java.io.Serializable {

	private int deviceid;
	private int geofenceid;

	public DeviceGeofenceId() {
	}

	public DeviceGeofenceId(int deviceid, int geofenceid) {
		this.deviceid = deviceid;
		this.geofenceid = geofenceid;
	}

	public int getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(int deviceid) {
		this.deviceid = deviceid;
	}

	public int getGeofenceid() {
		return this.geofenceid;
	}

	public void setGeofenceid(int geofenceid) {
		this.geofenceid = geofenceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceGeofenceId))
			return false;
		DeviceGeofenceId castOther = (DeviceGeofenceId) other;

		return (this.getDeviceid() == castOther.getDeviceid()) && (this.getGeofenceid() == castOther.getGeofenceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeviceid();
		result = 37 * result + this.getGeofenceid();
		return result;
	}

}
