package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private int id;
	private Devices devices;
	private String type;
	private Date servertime;
	private Integer positionid;
	private Integer geofenceid;
	private String attributes;

	public Events() {
	}

	public Events(int id, String type, Date servertime, String attributes) {
		this.id = id;
		this.type = type;
		this.servertime = servertime;
		this.attributes = attributes;
	}

	public Events(int id, Devices devices, String type, Date servertime, Integer positionid, Integer geofenceid,
			String attributes) {
		this.id = id;
		this.devices = devices;
		this.type = type;
		this.servertime = servertime;
		this.positionid = positionid;
		this.geofenceid = geofenceid;
		this.attributes = attributes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getServertime() {
		return this.servertime;
	}

	public void setServertime(Date servertime) {
		this.servertime = servertime;
	}

	public Integer getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Integer positionid) {
		this.positionid = positionid;
	}

	public Integer getGeofenceid() {
		return this.geofenceid;
	}

	public void setGeofenceid(Integer geofenceid) {
		this.geofenceid = geofenceid;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

//	org.hibernate.LazyInitializationException: could not initialize proxy - no Session
//	@Override
//	public String toString() {
//		return "Events [id=" + id + ", devices=" + devices + ", type=" + type + ", servertime=" + servertime
//				+ ", positionid=" + positionid + ", geofenceid=" + geofenceid + ", attributes=" + attributes + "]";
//	}

}
