package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private int id;
	private Groups groups;
	private String name;
	private String attributes;
	private Set<Groups> groupses = new HashSet<Groups>(0);
	private Set<Devices> deviceses = new HashSet<Devices>(0);
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
	private Set<GroupGeofence> groupGeofences = new HashSet<GroupGeofence>(0);

	public Groups() {
	}

	public Groups(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Groups(int id, Groups groups, String name, String attributes, Set<Groups> groupses, Set<Devices> deviceses,
			Set<UserGroup> userGroups, Set<GroupGeofence> groupGeofences) {
		this.id = id;
		this.groups = groups;
		this.name = name;
		this.attributes = attributes;
		this.groupses = groupses;
		this.deviceses = deviceses;
		this.userGroups = userGroups;
		this.groupGeofences = groupGeofences;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

	public Set<Devices> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
		this.deviceses = deviceses;
	}

	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}

	public Set<GroupGeofence> getGroupGeofences() {
		return this.groupGeofences;
	}

	public void setGroupGeofences(Set<GroupGeofence> groupGeofences) {
		this.groupGeofences = groupGeofences;
	}

}
