package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * Notifications generated by hbm2java
 */
public class Notifications implements java.io.Serializable {

	private int id;
	private Users users;
	private String type;
	private String attributes;

	public Notifications() {
	}

	public Notifications(int id, Users users, String type, String attributes) {
		this.id = id;
		this.users = users;
		this.type = type;
		this.attributes = attributes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

}
