package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * Server generated by hbm2java
 */
public class Server implements java.io.Serializable {

	private int id;
	private boolean registration;
	private double latitude;
	private double longitude;
	private int zoom;
	private String map;
	private String distanceunit;
	private String speedunit;
	private String bingkey;
	private String mapurl;
	private boolean readonly;
	private boolean twelvehourformat;
	private String attributes;
	private boolean forcesettings;
	private String coordinateformat;

	public Server() {
	}

	public Server(int id, boolean registration, double latitude, double longitude, int zoom, boolean readonly,
			boolean twelvehourformat, boolean forcesettings) {
		this.id = id;
		this.registration = registration;
		this.latitude = latitude;
		this.longitude = longitude;
		this.zoom = zoom;
		this.readonly = readonly;
		this.twelvehourformat = twelvehourformat;
		this.forcesettings = forcesettings;
	}

	public Server(int id, boolean registration, double latitude, double longitude, int zoom, String map,
			String distanceunit, String speedunit, String bingkey, String mapurl, boolean readonly,
			boolean twelvehourformat, String attributes, boolean forcesettings, String coordinateformat) {
		this.id = id;
		this.registration = registration;
		this.latitude = latitude;
		this.longitude = longitude;
		this.zoom = zoom;
		this.map = map;
		this.distanceunit = distanceunit;
		this.speedunit = speedunit;
		this.bingkey = bingkey;
		this.mapurl = mapurl;
		this.readonly = readonly;
		this.twelvehourformat = twelvehourformat;
		this.attributes = attributes;
		this.forcesettings = forcesettings;
		this.coordinateformat = coordinateformat;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isRegistration() {
		return this.registration;
	}

	public void setRegistration(boolean registration) {
		this.registration = registration;
	}

	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public int getZoom() {
		return this.zoom;
	}

	public void setZoom(int zoom) {
		this.zoom = zoom;
	}

	public String getMap() {
		return this.map;
	}

	public void setMap(String map) {
		this.map = map;
	}

	public String getDistanceunit() {
		return this.distanceunit;
	}

	public void setDistanceunit(String distanceunit) {
		this.distanceunit = distanceunit;
	}

	public String getSpeedunit() {
		return this.speedunit;
	}

	public void setSpeedunit(String speedunit) {
		this.speedunit = speedunit;
	}

	public String getBingkey() {
		return this.bingkey;
	}

	public void setBingkey(String bingkey) {
		this.bingkey = bingkey;
	}

	public String getMapurl() {
		return this.mapurl;
	}

	public void setMapurl(String mapurl) {
		this.mapurl = mapurl;
	}

	public boolean isReadonly() {
		return this.readonly;
	}

	public void setReadonly(boolean readonly) {
		this.readonly = readonly;
	}

	public boolean isTwelvehourformat() {
		return this.twelvehourformat;
	}

	public void setTwelvehourformat(boolean twelvehourformat) {
		this.twelvehourformat = twelvehourformat;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public boolean isForcesettings() {
		return this.forcesettings;
	}

	public void setForcesettings(boolean forcesettings) {
		this.forcesettings = forcesettings;
	}

	public String getCoordinateformat() {
		return this.coordinateformat;
	}

	public void setCoordinateformat(String coordinateformat) {
		this.coordinateformat = coordinateformat;
	}

}
