package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserGeofence generated by hbm2java
 */
public class UserGeofence implements java.io.Serializable {

	private UserGeofenceId id;
	private Geofences geofences;
	private Users users;

	public UserGeofence() {
	}

	public UserGeofence(UserGeofenceId id, Geofences geofences, Users users) {
		this.id = id;
		this.geofences = geofences;
		this.users = users;
	}

	public UserGeofenceId getId() {
		return this.id;
	}

	public void setId(UserGeofenceId id) {
		this.id = id;
	}

	public Geofences getGeofences() {
		return this.geofences;
	}

	public void setGeofences(Geofences geofences) {
		this.geofences = geofences;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
