package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private UserGroupId id;
	private Groups groups;
	private Users users;

	public UserGroup() {
	}

	public UserGroup(UserGroupId id, Groups groups, Users users) {
		this.id = id;
		this.groups = groups;
		this.users = users;
	}

	public UserGroupId getId() {
		return this.id;
	}

	public void setId(UserGroupId id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
