package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserGroupId generated by hbm2java
 */
public class UserGroupId implements java.io.Serializable {

	private int userid;
	private int groupid;

	public UserGroupId() {
	}

	public UserGroupId(int userid, int groupid) {
		this.userid = userid;
		this.groupid = groupid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getGroupid() {
		return this.groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupId))
			return false;
		UserGroupId castOther = (UserGroupId) other;

		return (this.getUserid() == castOther.getUserid()) && (this.getGroupid() == castOther.getGroupid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getGroupid();
		return result;
	}

}
