package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserDeviceId generated by hbm2java
 */
public class UserDeviceId implements java.io.Serializable {

	private int userid;
	private int deviceid;

	public UserDeviceId() {
	}

	public UserDeviceId(int userid, int deviceid) {
		this.userid = userid;
		this.deviceid = deviceid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(int deviceid) {
		this.deviceid = deviceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDeviceId))
			return false;
		UserDeviceId castOther = (UserDeviceId) other;

		return (this.getUserid() == castOther.getUserid()) && (this.getDeviceid() == castOther.getDeviceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getDeviceid();
		return result;
	}

}
