package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FareAttributes generated by hbm2java
 */
@Entity
@Table(name = "fare_attributes", schema = "public")
public class FareAttributes implements java.io.Serializable {

    private String fareId;
    private BigDecimal price;
    private String currencyType;
    private int paymentMethod;
    private Integer transfers;
    private Integer transferDuration;
    private String agencyId;

    public FareAttributes() {
    }

    public FareAttributes(String fareId, BigDecimal price, String currencyType, int paymentMethod) {
        this.fareId = fareId;
        this.price = price;
        this.currencyType = currencyType;
        this.paymentMethod = paymentMethod;
    }

    public FareAttributes(String fareId, BigDecimal price, String currencyType, int paymentMethod, Integer transfers,
            Integer transferDuration, String agencyId) {
        this.fareId = fareId;
        this.price = price;
        this.currencyType = currencyType;
        this.paymentMethod = paymentMethod;
        this.transfers = transfers;
        this.transferDuration = transferDuration;
        this.agencyId = agencyId;
    }

    @Id

    @Column(name = "fare_id", unique = true, nullable = false)
    public String getFareId() {
        return this.fareId;
    }

    public void setFareId(String fareId) {
        this.fareId = fareId;
    }

    @Column(name = "price", nullable = false, precision = 10)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "currency_type", nullable = false)
    public String getCurrencyType() {
        return this.currencyType;
    }

    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    @Column(name = "payment_method", nullable = false)
    public int getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setPaymentMethod(int paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @Column(name = "transfers")
    public Integer getTransfers() {
        return this.transfers;
    }

    public void setTransfers(Integer transfers) {
        this.transfers = transfers;
    }

    @Column(name = "transfer_duration")
    public Integer getTransferDuration() {
        return this.transferDuration;
    }

    public void setTransferDuration(Integer transferDuration) {
        this.transferDuration = transferDuration;
    }

    @Column(name = "agency_id")
    public String getAgencyId() {
        return this.agencyId;
    }

    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId;
    }

}
