package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FrequenciesId generated by hbm2java
 */
@Embeddable
public class FrequenciesId implements java.io.Serializable {

    private String tripId;
    private String startTime;

    public FrequenciesId() {
    }

    public FrequenciesId(String tripId, String startTime) {
        this.tripId = tripId;
        this.startTime = startTime;
    }

    @Column(name = "trip_id", nullable = false)
    public String getTripId() {
        return this.tripId;
    }

    public void setTripId(String tripId) {
        this.tripId = tripId;
    }

    @Column(name = "start_time", nullable = false, length = 8)
    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FrequenciesId))
            return false;
        FrequenciesId castOther = (FrequenciesId) other;

        return ((this.getTripId() == castOther.getTripId()) || (this.getTripId() != null
                && castOther.getTripId() != null && this.getTripId().equals(castOther.getTripId())))
                && ((this.getStartTime() == castOther.getStartTime()) || (this.getStartTime() != null
                        && castOther.getStartTime() != null && this.getStartTime().equals(castOther.getStartTime())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTripId() == null ? 0 : this.getTripId().hashCode());
        result = 37 * result + (getStartTime() == null ? 0 : this.getStartTime().hashCode());
        return result;
    }

}
