package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RasterOverviewsId generated by hbm2java
 */
@Embeddable
public class RasterOverviewsId implements java.io.Serializable {

    private String OTableCatalog;
    private String OTableSchema;
    private String OTableName;
    private String ORasterColumn;
    private String RTableCatalog;
    private String RTableSchema;
    private String RTableName;
    private String RRasterColumn;
    private Integer overviewFactor;

    public RasterOverviewsId() {
    }

    public RasterOverviewsId(String OTableCatalog, String OTableSchema, String OTableName, String ORasterColumn,
            String RTableCatalog, String RTableSchema, String RTableName, String RRasterColumn,
            Integer overviewFactor) {
        this.OTableCatalog = OTableCatalog;
        this.OTableSchema = OTableSchema;
        this.OTableName = OTableName;
        this.ORasterColumn = ORasterColumn;
        this.RTableCatalog = RTableCatalog;
        this.RTableSchema = RTableSchema;
        this.RTableName = RTableName;
        this.RRasterColumn = RRasterColumn;
        this.overviewFactor = overviewFactor;
    }

    @Column(name = "o_table_catalog")
    public String getOTableCatalog() {
        return this.OTableCatalog;
    }

    public void setOTableCatalog(String OTableCatalog) {
        this.OTableCatalog = OTableCatalog;
    }

    @Column(name = "o_table_schema")
    public String getOTableSchema() {
        return this.OTableSchema;
    }

    public void setOTableSchema(String OTableSchema) {
        this.OTableSchema = OTableSchema;
    }

    @Column(name = "o_table_name")
    public String getOTableName() {
        return this.OTableName;
    }

    public void setOTableName(String OTableName) {
        this.OTableName = OTableName;
    }

    @Column(name = "o_raster_column")
    public String getORasterColumn() {
        return this.ORasterColumn;
    }

    public void setORasterColumn(String ORasterColumn) {
        this.ORasterColumn = ORasterColumn;
    }

    @Column(name = "r_table_catalog")
    public String getRTableCatalog() {
        return this.RTableCatalog;
    }

    public void setRTableCatalog(String RTableCatalog) {
        this.RTableCatalog = RTableCatalog;
    }

    @Column(name = "r_table_schema")
    public String getRTableSchema() {
        return this.RTableSchema;
    }

    public void setRTableSchema(String RTableSchema) {
        this.RTableSchema = RTableSchema;
    }

    @Column(name = "r_table_name")
    public String getRTableName() {
        return this.RTableName;
    }

    public void setRTableName(String RTableName) {
        this.RTableName = RTableName;
    }

    @Column(name = "r_raster_column")
    public String getRRasterColumn() {
        return this.RRasterColumn;
    }

    public void setRRasterColumn(String RRasterColumn) {
        this.RRasterColumn = RRasterColumn;
    }

    @Column(name = "overview_factor")
    public Integer getOverviewFactor() {
        return this.overviewFactor;
    }

    public void setOverviewFactor(Integer overviewFactor) {
        this.overviewFactor = overviewFactor;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RasterOverviewsId))
            return false;
        RasterOverviewsId castOther = (RasterOverviewsId) other;

        return ((this.getOTableCatalog() == castOther.getOTableCatalog())
                || (this.getOTableCatalog() != null && castOther.getOTableCatalog() != null
                        && this.getOTableCatalog().equals(castOther.getOTableCatalog())))
                && ((this.getOTableSchema() == castOther.getOTableSchema())
                        || (this.getOTableSchema() != null && castOther.getOTableSchema() != null
                                && this.getOTableSchema().equals(castOther.getOTableSchema())))
                && ((this.getOTableName() == castOther.getOTableName()) || (this.getOTableName() != null
                        && castOther.getOTableName() != null && this.getOTableName().equals(castOther.getOTableName())))
                && ((this.getORasterColumn() == castOther.getORasterColumn())
                        || (this.getORasterColumn() != null && castOther.getORasterColumn() != null
                                && this.getORasterColumn().equals(castOther.getORasterColumn())))
                && ((this.getRTableCatalog() == castOther.getRTableCatalog())
                        || (this.getRTableCatalog() != null && castOther.getRTableCatalog() != null
                                && this.getRTableCatalog().equals(castOther.getRTableCatalog())))
                && ((this.getRTableSchema() == castOther.getRTableSchema())
                        || (this.getRTableSchema() != null && castOther.getRTableSchema() != null
                                && this.getRTableSchema().equals(castOther.getRTableSchema())))
                && ((this.getRTableName() == castOther.getRTableName()) || (this.getRTableName() != null
                        && castOther.getRTableName() != null && this.getRTableName().equals(castOther.getRTableName())))
                && ((this.getRRasterColumn() == castOther.getRRasterColumn())
                        || (this.getRRasterColumn() != null && castOther.getRRasterColumn() != null
                                && this.getRRasterColumn().equals(castOther.getRRasterColumn())))
                && ((this.getOverviewFactor() == castOther.getOverviewFactor())
                        || (this.getOverviewFactor() != null && castOther.getOverviewFactor() != null
                                && this.getOverviewFactor().equals(castOther.getOverviewFactor())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getOTableCatalog() == null ? 0 : this.getOTableCatalog().hashCode());
        result = 37 * result + (getOTableSchema() == null ? 0 : this.getOTableSchema().hashCode());
        result = 37 * result + (getOTableName() == null ? 0 : this.getOTableName().hashCode());
        result = 37 * result + (getORasterColumn() == null ? 0 : this.getORasterColumn().hashCode());
        result = 37 * result + (getRTableCatalog() == null ? 0 : this.getRTableCatalog().hashCode());
        result = 37 * result + (getRTableSchema() == null ? 0 : this.getRTableSchema().hashCode());
        result = 37 * result + (getRTableName() == null ? 0 : this.getRTableName().hashCode());
        result = 37 * result + (getRRasterColumn() == null ? 0 : this.getRRasterColumn().hashCode());
        result = 37 * result + (getOverviewFactor() == null ? 0 : this.getOverviewFactor().hashCode());
        return result;
    }

}
