package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RasterColumnsId generated by hbm2java
 */
@Embeddable
public class RasterColumnsId implements java.io.Serializable {

    private String RTableCatalog;
    private String RTableSchema;
    private String RTableName;
    private String RRasterColumn;
    private Integer srid;
    private Double scaleX;
    private Double scaleY;
    private Integer blocksizeX;
    private Integer blocksizeY;
    private Boolean sameAlignment;
    private Boolean regularBlocking;
    private Integer numBands;
    private Serializable pixelTypes;
    private Serializable nodataValues;
    private Serializable outDb;
    private Serializable extent;
    private Boolean spatialIndex;

    public RasterColumnsId() {
    }

    public RasterColumnsId(String RTableCatalog, String RTableSchema, String RTableName, String RRasterColumn,
            Integer srid, Double scaleX, Double scaleY, Integer blocksizeX, Integer blocksizeY, Boolean sameAlignment,
            Boolean regularBlocking, Integer numBands, Serializable pixelTypes, Serializable nodataValues,
            Serializable outDb, Serializable extent, Boolean spatialIndex) {
        this.RTableCatalog = RTableCatalog;
        this.RTableSchema = RTableSchema;
        this.RTableName = RTableName;
        this.RRasterColumn = RRasterColumn;
        this.srid = srid;
        this.scaleX = scaleX;
        this.scaleY = scaleY;
        this.blocksizeX = blocksizeX;
        this.blocksizeY = blocksizeY;
        this.sameAlignment = sameAlignment;
        this.regularBlocking = regularBlocking;
        this.numBands = numBands;
        this.pixelTypes = pixelTypes;
        this.nodataValues = nodataValues;
        this.outDb = outDb;
        this.extent = extent;
        this.spatialIndex = spatialIndex;
    }

    @Column(name = "r_table_catalog")
    public String getRTableCatalog() {
        return this.RTableCatalog;
    }

    public void setRTableCatalog(String RTableCatalog) {
        this.RTableCatalog = RTableCatalog;
    }

    @Column(name = "r_table_schema")
    public String getRTableSchema() {
        return this.RTableSchema;
    }

    public void setRTableSchema(String RTableSchema) {
        this.RTableSchema = RTableSchema;
    }

    @Column(name = "r_table_name")
    public String getRTableName() {
        return this.RTableName;
    }

    public void setRTableName(String RTableName) {
        this.RTableName = RTableName;
    }

    @Column(name = "r_raster_column")
    public String getRRasterColumn() {
        return this.RRasterColumn;
    }

    public void setRRasterColumn(String RRasterColumn) {
        this.RRasterColumn = RRasterColumn;
    }

    @Column(name = "srid")
    public Integer getSrid() {
        return this.srid;
    }

    public void setSrid(Integer srid) {
        this.srid = srid;
    }

    @Column(name = "scale_x", precision = 17, scale = 17)
    public Double getScaleX() {
        return this.scaleX;
    }

    public void setScaleX(Double scaleX) {
        this.scaleX = scaleX;
    }

    @Column(name = "scale_y", precision = 17, scale = 17)
    public Double getScaleY() {
        return this.scaleY;
    }

    public void setScaleY(Double scaleY) {
        this.scaleY = scaleY;
    }

    @Column(name = "blocksize_x")
    public Integer getBlocksizeX() {
        return this.blocksizeX;
    }

    public void setBlocksizeX(Integer blocksizeX) {
        this.blocksizeX = blocksizeX;
    }

    @Column(name = "blocksize_y")
    public Integer getBlocksizeY() {
        return this.blocksizeY;
    }

    public void setBlocksizeY(Integer blocksizeY) {
        this.blocksizeY = blocksizeY;
    }

    @Column(name = "same_alignment")
    public Boolean getSameAlignment() {
        return this.sameAlignment;
    }

    public void setSameAlignment(Boolean sameAlignment) {
        this.sameAlignment = sameAlignment;
    }

    @Column(name = "regular_blocking")
    public Boolean getRegularBlocking() {
        return this.regularBlocking;
    }

    public void setRegularBlocking(Boolean regularBlocking) {
        this.regularBlocking = regularBlocking;
    }

    @Column(name = "num_bands")
    public Integer getNumBands() {
        return this.numBands;
    }

    public void setNumBands(Integer numBands) {
        this.numBands = numBands;
    }

    @Column(name = "pixel_types")
    public Serializable getPixelTypes() {
        return this.pixelTypes;
    }

    public void setPixelTypes(Serializable pixelTypes) {
        this.pixelTypes = pixelTypes;
    }

    @Column(name = "nodata_values")
    public Serializable getNodataValues() {
        return this.nodataValues;
    }

    public void setNodataValues(Serializable nodataValues) {
        this.nodataValues = nodataValues;
    }

    @Column(name = "out_db")
    public Serializable getOutDb() {
        return this.outDb;
    }

    public void setOutDb(Serializable outDb) {
        this.outDb = outDb;
    }

    @Column(name = "extent")
    public Serializable getExtent() {
        return this.extent;
    }

    public void setExtent(Serializable extent) {
        this.extent = extent;
    }

    @Column(name = "spatial_index")
    public Boolean getSpatialIndex() {
        return this.spatialIndex;
    }

    public void setSpatialIndex(Boolean spatialIndex) {
        this.spatialIndex = spatialIndex;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RasterColumnsId))
            return false;
        RasterColumnsId castOther = (RasterColumnsId) other;

        return ((this.getRTableCatalog() == castOther.getRTableCatalog())
                || (this.getRTableCatalog() != null && castOther.getRTableCatalog() != null
                        && this.getRTableCatalog().equals(castOther.getRTableCatalog())))
                && ((this.getRTableSchema() == castOther.getRTableSchema())
                        || (this.getRTableSchema() != null && castOther.getRTableSchema() != null
                                && this.getRTableSchema().equals(castOther.getRTableSchema())))
                && ((this.getRTableName() == castOther.getRTableName()) || (this.getRTableName() != null
                        && castOther.getRTableName() != null && this.getRTableName().equals(castOther.getRTableName())))
                && ((this.getRRasterColumn() == castOther.getRRasterColumn())
                        || (this.getRRasterColumn() != null && castOther.getRRasterColumn() != null
                                && this.getRRasterColumn().equals(castOther.getRRasterColumn())))
                && ((this.getSrid() == castOther.getSrid()) || (this.getSrid() != null && castOther.getSrid() != null
                        && this.getSrid().equals(castOther.getSrid())))
                && ((this.getScaleX() == castOther.getScaleX()) || (this.getScaleX() != null
                        && castOther.getScaleX() != null && this.getScaleX().equals(castOther.getScaleX())))
                && ((this.getScaleY() == castOther.getScaleY()) || (this.getScaleY() != null
                        && castOther.getScaleY() != null && this.getScaleY().equals(castOther.getScaleY())))
                && ((this.getBlocksizeX() == castOther.getBlocksizeX()) || (this.getBlocksizeX() != null
                        && castOther.getBlocksizeX() != null && this.getBlocksizeX().equals(castOther.getBlocksizeX())))
                && ((this.getBlocksizeY() == castOther.getBlocksizeY()) || (this.getBlocksizeY() != null
                        && castOther.getBlocksizeY() != null && this.getBlocksizeY().equals(castOther.getBlocksizeY())))
                && ((this.getSameAlignment() == castOther.getSameAlignment())
                        || (this.getSameAlignment() != null && castOther.getSameAlignment() != null
                                && this.getSameAlignment().equals(castOther.getSameAlignment())))
                && ((this.getRegularBlocking() == castOther.getRegularBlocking())
                        || (this.getRegularBlocking() != null && castOther.getRegularBlocking() != null
                                && this.getRegularBlocking().equals(castOther.getRegularBlocking())))
                && ((this.getNumBands() == castOther.getNumBands()) || (this.getNumBands() != null
                        && castOther.getNumBands() != null && this.getNumBands().equals(castOther.getNumBands())))
                && ((this.getPixelTypes() == castOther.getPixelTypes()) || (this.getPixelTypes() != null
                        && castOther.getPixelTypes() != null && this.getPixelTypes().equals(castOther.getPixelTypes())))
                && ((this.getNodataValues() == castOther.getNodataValues())
                        || (this.getNodataValues() != null && castOther.getNodataValues() != null
                                && this.getNodataValues().equals(castOther.getNodataValues())))
                && ((this.getOutDb() == castOther.getOutDb()) || (this.getOutDb() != null
                        && castOther.getOutDb() != null && this.getOutDb().equals(castOther.getOutDb())))
                && ((this.getExtent() == castOther.getExtent()) || (this.getExtent() != null
                        && castOther.getExtent() != null && this.getExtent().equals(castOther.getExtent())))
                && ((this.getSpatialIndex() == castOther.getSpatialIndex())
                        || (this.getSpatialIndex() != null && castOther.getSpatialIndex() != null
                                && this.getSpatialIndex().equals(castOther.getSpatialIndex())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getRTableCatalog() == null ? 0 : this.getRTableCatalog().hashCode());
        result = 37 * result + (getRTableSchema() == null ? 0 : this.getRTableSchema().hashCode());
        result = 37 * result + (getRTableName() == null ? 0 : this.getRTableName().hashCode());
        result = 37 * result + (getRRasterColumn() == null ? 0 : this.getRRasterColumn().hashCode());
        result = 37 * result + (getSrid() == null ? 0 : this.getSrid().hashCode());
        result = 37 * result + (getScaleX() == null ? 0 : this.getScaleX().hashCode());
        result = 37 * result + (getScaleY() == null ? 0 : this.getScaleY().hashCode());
        result = 37 * result + (getBlocksizeX() == null ? 0 : this.getBlocksizeX().hashCode());
        result = 37 * result + (getBlocksizeY() == null ? 0 : this.getBlocksizeY().hashCode());
        result = 37 * result + (getSameAlignment() == null ? 0 : this.getSameAlignment().hashCode());
        result = 37 * result + (getRegularBlocking() == null ? 0 : this.getRegularBlocking().hashCode());
        result = 37 * result + (getNumBands() == null ? 0 : this.getNumBands().hashCode());
        result = 37 * result + (getPixelTypes() == null ? 0 : this.getPixelTypes().hashCode());
        result = 37 * result + (getNodataValues() == null ? 0 : this.getNodataValues().hashCode());
        result = 37 * result + (getOutDb() == null ? 0 : this.getOutDb().hashCode());
        result = 37 * result + (getExtent() == null ? 0 : this.getExtent().hashCode());
        result = 37 * result + (getSpatialIndex() == null ? 0 : this.getSpatialIndex().hashCode());
        return result;
    }

}
