package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RouteTrips generated by hbm2java
 */
@Entity
@Table(name = "route_trips", schema = "public")
public class RouteTrips implements java.io.Serializable {

    private RouteTripsId id;

    public RouteTrips() {
    }

    public RouteTrips(RouteTripsId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "tripId", column = @Column(name = "trip_id")),
            @AttributeOverride(name = "routeId", column = @Column(name = "route_id")),
            @AttributeOverride(name = "serviceId", column = @Column(name = "service_id")),
            @AttributeOverride(name = "directionId", column = @Column(name = "direction_id")),
            @AttributeOverride(name = "blockId", column = @Column(name = "block_id")),
            @AttributeOverride(name = "shapeId", column = @Column(name = "shape_id")),
            @AttributeOverride(name = "tripType", column = @Column(name = "trip_type")),
            @AttributeOverride(name = "tripHeadsign", column = @Column(name = "trip_headsign")),
            @AttributeOverride(name = "tripShortName", column = @Column(name = "trip_short_name")),
            @AttributeOverride(name = "bikesAllowed", column = @Column(name = "bikes_allowed")),
            @AttributeOverride(name = "wheelchairAccessible", column = @Column(name = "wheelchair_accessible")) })
    public RouteTripsId getId() {
        return this.id;
    }

    public void setId(RouteTripsId id) {
        this.id = id;
    }

}
