package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RouteDirectionsId generated by hbm2java
 */
@Embeddable
public class RouteDirectionsId implements java.io.Serializable {

    private String routeId;
    private int directionId;

    public RouteDirectionsId() {
    }

    public RouteDirectionsId(String routeId, int directionId) {
        this.routeId = routeId;
        this.directionId = directionId;
    }

    @Column(name = "route_id", nullable = false)
    public String getRouteId() {
        return this.routeId;
    }

    public void setRouteId(String routeId) {
        this.routeId = routeId;
    }

    @Column(name = "direction_id", nullable = false)
    public int getDirectionId() {
        return this.directionId;
    }

    public void setDirectionId(int directionId) {
        this.directionId = directionId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RouteDirectionsId))
            return false;
        RouteDirectionsId castOther = (RouteDirectionsId) other;

        return ((this.getRouteId() == castOther.getRouteId()) || (this.getRouteId() != null
                && castOther.getRouteId() != null && this.getRouteId().equals(castOther.getRouteId())))
                && (this.getDirectionId() == castOther.getDirectionId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getRouteId() == null ? 0 : this.getRouteId().hashCode());
        result = 37 * result + this.getDirectionId();
        return result;
    }

}
