package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShapesId generated by hbm2java
 */
@Embeddable
public class ShapesId implements java.io.Serializable {

    private String shapeId;
    private int shapePtSequence;

    public ShapesId() {
    }

    public ShapesId(String shapeId, int shapePtSequence) {
        this.shapeId = shapeId;
        this.shapePtSequence = shapePtSequence;
    }

    @Column(name = "shape_id", nullable = false)
    public String getShapeId() {
        return this.shapeId;
    }

    public void setShapeId(String shapeId) {
        this.shapeId = shapeId;
    }

    @Column(name = "shape_pt_sequence", nullable = false)
    public int getShapePtSequence() {
        return this.shapePtSequence;
    }

    public void setShapePtSequence(int shapePtSequence) {
        this.shapePtSequence = shapePtSequence;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ShapesId))
            return false;
        ShapesId castOther = (ShapesId) other;

        return ((this.getShapeId() == castOther.getShapeId()) || (this.getShapeId() != null
                && castOther.getShapeId() != null && this.getShapeId().equals(castOther.getShapeId())))
                && (this.getShapePtSequence() == castOther.getShapePtSequence());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getShapeId() == null ? 0 : this.getShapeId().hashCode());
        result = 37 * result + this.getShapePtSequence();
        return result;
    }

}
