package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StopTimesId generated by hbm2java
 */
@Embeddable
public class StopTimesId implements java.io.Serializable {

    private String tripId;
    private int stopSequence;

    public StopTimesId() {
    }

    public StopTimesId(String tripId, int stopSequence) {
        this.tripId = tripId;
        this.stopSequence = stopSequence;
    }

    @Column(name = "trip_id", nullable = false)
    public String getTripId() {
        return this.tripId;
    }

    public void setTripId(String tripId) {
        this.tripId = tripId;
    }

    @Column(name = "stop_sequence", nullable = false)
    public int getStopSequence() {
        return this.stopSequence;
    }

    public void setStopSequence(int stopSequence) {
        this.stopSequence = stopSequence;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof StopTimesId))
            return false;
        StopTimesId castOther = (StopTimesId) other;

        return ((this.getTripId() == castOther.getTripId()) || (this.getTripId() != null
                && castOther.getTripId() != null && this.getTripId().equals(castOther.getTripId())))
                && (this.getStopSequence() == castOther.getStopSequence());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTripId() == null ? 0 : this.getTripId().hashCode());
        result = 37 * result + this.getStopSequence();
        return result;
    }

}
