package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calendars generated by hbm2java
 */
@Entity
@Table(name = "calendars", schema = "public")
public class Calendars implements java.io.Serializable {

    private int id;
    private String name;
    private String attributes;
    private byte[] data;
    private Set<Geofence> geofenceses = new HashSet<Geofence>(0);
    private Set<UserCalendar> userCalendars = new HashSet<UserCalendar>(0);

    public Calendars() {
    }

    public Calendars(int id, String name, String attributes, byte[] data) {
        this.id = id;
        this.name = name;
        this.attributes = attributes;
        this.data = data;
    }

    public Calendars(int id, String name, String attributes, byte[] data, Set<Geofence> geofenceses,
            Set<UserCalendar> userCalendars) {
        this.id = id;
        this.name = name;
        this.attributes = attributes;
        this.data = data;
        this.geofenceses = geofenceses;
        this.userCalendars = userCalendars;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "attributes", nullable = false, length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Column(name = "data", nullable = false)
    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "calendars")
    public Set<Geofence> getGeofenceses() {
        return this.geofenceses;
    }

    public void setGeofenceses(Set<Geofence> geofenceses) {
        this.geofenceses = geofenceses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "calendars")
    public Set<UserCalendar> getUserCalendars() {
        return this.userCalendars;
    }

    public void setUserCalendars(Set<UserCalendar> userCalendars) {
        this.userCalendars = userCalendars;
    }

}
