package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeviceAttribute generated by hbm2java
 */
@Entity
@Table(name = "device_attribute", schema = "public")
public class DeviceAttribute implements java.io.Serializable {

    private DeviceAttributeId id;
    private Attributes attributes;
    private Devices devices;

    public DeviceAttribute() {
    }

    public DeviceAttribute(DeviceAttributeId id, Attributes attributes, Devices devices) {
        this.id = id;
        this.attributes = attributes;
        this.devices = devices;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "deviceid", column = @Column(name = "deviceid", nullable = false)),
            @AttributeOverride(name = "attributeid", column = @Column(name = "attributeid", nullable = false)) })
    public DeviceAttributeId getId() {
        return this.id;
    }

    public void setId(DeviceAttributeId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributeid", nullable = false, insertable = false, updatable = false)
    public Attributes getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid", nullable = false, insertable = false, updatable = false)
    public Devices getDevices() {
        return this.devices;
    }

    public void setDevices(Devices devices) {
        this.devices = devices;
    }

}
