package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", schema = "public")
public class Events implements java.io.Serializable {

    private int id;
    private Devices devices;
    private String type;
    private Date servertime;
    private Integer positionid;
    private Integer geofenceid;
    private String attributes;

    public Events() {
    }

    public Events(int id, String type, Date servertime) {
        this.id = id;
        this.type = type;
        this.servertime = servertime;
    }

    public Events(int id, Devices devices, String type, Date servertime, Integer positionid, Integer geofenceid,
            String attributes) {
        this.id = id;
        this.devices = devices;
        this.type = type;
        this.servertime = servertime;
        this.positionid = positionid;
        this.geofenceid = geofenceid;
        this.attributes = attributes;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid")
    public Devices getDevices() {
        return this.devices;
    }

    public void setDevices(Devices devices) {
        this.devices = devices;
    }

    @Column(name = "type", nullable = false, length = 128)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "servertime", nullable = false, length = 29)
    public Date getServertime() {
        return this.servertime;
    }

    public void setServertime(Date servertime) {
        this.servertime = servertime;
    }

    @Column(name = "positionid")
    public Integer getPositionid() {
        return this.positionid;
    }

    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    @Column(name = "geofenceid")
    public Integer getGeofenceid() {
        return this.geofenceid;
    }

    public void setGeofenceid(Integer geofenceid) {
        this.geofenceid = geofenceid;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

}
