package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
//import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Geofences generated by hbm2java
 */
@Entity
@Table(name = "geofences", schema = "public")
//@NamedQuery(name = "findGeofenceById", query = "SELECT g FROM Geofence g WHERE g.id = :id")
public class Geofence implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int id;
//    private Calendars calendars;
    private String name;
    private String description;
    private String area;
    private String attributes;
    private Set<DeviceGeofence> deviceGeofences = new HashSet<DeviceGeofence>(0);
//    private Set<GroupGeofence> groupGeofences = new HashSet<GroupGeofence>(0);
//    private Set<UserGeofence> userGeofences = new HashSet<UserGeofence>(0);

    public Geofence() {
    }

    public Geofence(int id, String name, String area) {
        this.id = id;
        this.name = name;
        this.area = area;
    }

    public Geofence(int id, Calendars calendars, String name, String description, String area, String attributes,
            Set<DeviceGeofence> deviceGeofences, Set<GroupGeofence> groupGeofences, Set<UserGeofence> userGeofences) {
        this.id = id;
//        this.calendars = calendars;
        this.name = name;
        this.description = description;
        this.area = area;
        this.attributes = attributes;
        this.deviceGeofences = deviceGeofences;
//        this.groupGeofences = groupGeofences;
//        this.userGeofences = userGeofences;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
/*
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "calendarid")
    public Calendars getCalendars() {
        return this.calendars;
    }

    public void setCalendars(Calendars calendars) {
        this.calendars = calendars;
    }
 */
    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 128)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "area", nullable = false, length = 4096)
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "geofence")
    public Set<DeviceGeofence> getDeviceGeofences() {
        return this.deviceGeofences;
    }

    public void setDeviceGeofences(Set<DeviceGeofence> deviceGeofences) {
        this.deviceGeofences = deviceGeofences;
    }
/*
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "geofences")
    public Set<GroupGeofence> getGroupGeofences() {
        return this.groupGeofences;
    }

    public void setGroupGeofences(Set<GroupGeofence> groupGeofences) {
        this.groupGeofences = groupGeofences;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "geofences")
    public Set<UserGeofence> getUserGeofences() {
        return this.userGeofences;
    }

    public void setUserGeofences(Set<UserGeofence> userGeofences) {
        this.userGeofences = userGeofences;
    }
 */
}
