package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupGeofence generated by hbm2java
 */
@Entity
@Table(name = "group_geofence", schema = "public")
public class GroupGeofence implements java.io.Serializable {

    private GroupGeofenceId id;
    private Geofence geofences;
    private Groups groups;

    public GroupGeofence() {
    }

    public GroupGeofence(GroupGeofenceId id, Geofence geofences, Groups groups) {
        this.id = id;
        this.geofences = geofences;
        this.groups = groups;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)),
            @AttributeOverride(name = "geofenceid", column = @Column(name = "geofenceid", nullable = false)) })
    public GroupGeofenceId getId() {
        return this.id;
    }

    public void setId(GroupGeofenceId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geofenceid", nullable = false, insertable = false, updatable = false)
    public Geofence getGeofences() {
        return this.geofences;
    }

    public void setGeofences(Geofence geofences) {
        this.geofences = geofences;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "groupid", nullable = false, insertable = false, updatable = false)
    public Groups getGroups() {
        return this.groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

}
