package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupAttribute generated by hbm2java
 */
@Entity
@Table(name = "group_attribute", schema = "public")
public class GroupAttribute implements java.io.Serializable {

    private GroupAttributeId id;
    private Attributes attributes;
    private Groups groups;

    public GroupAttribute() {
    }

    public GroupAttribute(GroupAttributeId id, Attributes attributes, Groups groups) {
        this.id = id;
        this.attributes = attributes;
        this.groups = groups;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)),
            @AttributeOverride(name = "attributeid", column = @Column(name = "attributeid", nullable = false)) })
    public GroupAttributeId getId() {
        return this.id;
    }

    public void setId(GroupAttributeId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributeid", nullable = false, insertable = false, updatable = false)
    public Attributes getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "groupid", nullable = false, insertable = false, updatable = false)
    public Groups getGroups() {
        return this.groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

}
