package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGroup generated by hbm2java
 */
@Entity
@Table(name = "user_group", schema = "public")
public class UserGroup implements java.io.Serializable {

    private UserGroupId id;
    private Groups groups;
    private Users users;

    public UserGroup() {
    }

    public UserGroup(UserGroupId id, Groups groups, Users users) {
        this.id = id;
        this.groups = groups;
        this.users = users;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)) })
    public UserGroupId getId() {
        return this.id;
    }

    public void setId(UserGroupId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "groupid", nullable = false, insertable = false, updatable = false)
    public Groups getGroups() {
        return this.groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
