package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserDriver generated by hbm2java
 */
@Entity
@Table(name = "user_driver", schema = "public")
public class UserDriver implements java.io.Serializable {

    private UserDriverId id;
    private Drivers drivers;
    private Users users;

    public UserDriver() {
    }

    public UserDriver(UserDriverId id, Drivers drivers, Users users) {
        this.id = id;
        this.drivers = drivers;
        this.users = users;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "driverid", column = @Column(name = "driverid", nullable = false)) })
    public UserDriverId getId() {
        return this.id;
    }

    public void setId(UserDriverId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driverid", nullable = false, insertable = false, updatable = false)
    public Drivers getDrivers() {
        return this.drivers;
    }

    public void setDrivers(Drivers drivers) {
        this.drivers = drivers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
