package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserDriverId generated by hbm2java
 */
@Embeddable
public class UserDriverId implements java.io.Serializable {

    private int userid;
    private int driverid;

    public UserDriverId() {
    }

    public UserDriverId(int userid, int driverid) {
        this.userid = userid;
        this.driverid = driverid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "driverid", nullable = false)
    public int getDriverid() {
        return this.driverid;
    }

    public void setDriverid(int driverid) {
        this.driverid = driverid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserDriverId))
            return false;
        UserDriverId castOther = (UserDriverId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getDriverid() == castOther.getDriverid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getDriverid();
        return result;
    }

}
