package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAttribute generated by hbm2java
 */
@Entity
@Table(name = "user_attribute", schema = "public")
public class UserAttribute implements java.io.Serializable {

    private UserAttributeId id;
    private Attributes attributes;
    private Users users;

    public UserAttribute() {
    }

    public UserAttribute(UserAttributeId id, Attributes attributes, Users users) {
        this.id = id;
        this.attributes = attributes;
        this.users = users;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "attributeid", column = @Column(name = "attributeid", nullable = false)) })
    public UserAttributeId getId() {
        return this.id;
    }

    public void setId(UserAttributeId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributeid", nullable = false, insertable = false, updatable = false)
    public Attributes getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
