package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserGeofenceId generated by hbm2java
 */
@Embeddable
public class UserGeofenceId implements java.io.Serializable {

    private int userid;
    private int geofenceid;

    public UserGeofenceId() {
    }

    public UserGeofenceId(int userid, int geofenceid) {
        this.userid = userid;
        this.geofenceid = geofenceid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "geofenceid", nullable = false)
    public int getGeofenceid() {
        return this.geofenceid;
    }

    public void setGeofenceid(int geofenceid) {
        this.geofenceid = geofenceid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserGeofenceId))
            return false;
        UserGeofenceId castOther = (UserGeofenceId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getGeofenceid() == castOther.getGeofenceid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getGeofenceid();
        return result;
    }

}
