package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeviceDriverId generated by hbm2java
 */
@Embeddable
public class DeviceDriverId implements java.io.Serializable {

    private int deviceid;
    private int driverid;

    public DeviceDriverId() {
    }

    public DeviceDriverId(int deviceid, int driverid) {
        this.deviceid = deviceid;
        this.driverid = driverid;
    }

    @Column(name = "deviceid", nullable = false)
    public int getDeviceid() {
        return this.deviceid;
    }

    public void setDeviceid(int deviceid) {
        this.deviceid = deviceid;
    }

    @Column(name = "driverid", nullable = false)
    public int getDriverid() {
        return this.driverid;
    }

    public void setDriverid(int driverid) {
        this.driverid = driverid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DeviceDriverId))
            return false;
        DeviceDriverId castOther = (DeviceDriverId) other;

        return (this.getDeviceid() == castOther.getDeviceid()) && (this.getDriverid() == castOther.getDriverid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getDeviceid();
        result = 37 * result + this.getDriverid();
        return result;
    }

}
