package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeviceGeofence generated by hbm2java
 */
@Entity
@Table(name = "device_geofence", schema = "public")
public class DeviceGeofence implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private DeviceGeofenceId id;
    private Device device;
    private Geofence geofences;

    public DeviceGeofence() {
    }

    public DeviceGeofence(DeviceGeofenceId id, Device device, Geofence geofences) {
        this.id = id;
        this.device = device;
        this.geofences = geofences;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "deviceid", column = @Column(name = "deviceid", nullable = false)),
            @AttributeOverride(name = "geofenceid", column = @Column(name = "geofenceid", nullable = false)) })
    public DeviceGeofenceId getId() {
        return this.id;
    }

    public void setId(DeviceGeofenceId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid", nullable = false, insertable = false, updatable = false)
    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "geofenceid", nullable = false, insertable = false, updatable = false)
    public Geofence getGeofences() {
        return this.geofences;
    }

    public void setGeofences(Geofence geofences) {
        this.geofences = geofences;
    }

}
