package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeviceAttributeId generated by hbm2java
 */
@Embeddable
public class DeviceAttributeId implements java.io.Serializable {

    private int deviceid;
    private int attributeid;

    public DeviceAttributeId() {
    }

    public DeviceAttributeId(int deviceid, int attributeid) {
        this.deviceid = deviceid;
        this.attributeid = attributeid;
    }

    @Column(name = "deviceid", nullable = false)
    public int getDeviceid() {
        return this.deviceid;
    }

    public void setDeviceid(int deviceid) {
        this.deviceid = deviceid;
    }

    @Column(name = "attributeid", nullable = false)
    public int getAttributeid() {
        return this.attributeid;
    }

    public void setAttributeid(int attributeid) {
        this.attributeid = attributeid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DeviceAttributeId))
            return false;
        DeviceAttributeId castOther = (DeviceAttributeId) other;

        return (this.getDeviceid() == castOther.getDeviceid()) && (this.getAttributeid() == castOther.getAttributeid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getDeviceid();
        result = 37 * result + this.getAttributeid();
        return result;
    }

}
