package org.jeets.model.traccar.jpa;
// Generated 20.02.2017 21:12:15 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", schema = "public")
public class Event implements java.io.Serializable {

    // TODO: change positionid and geofenceid to entity relations (see device)
    // and create test case in PU (see GeofenceManager/Test, 
    // Georouter (introduced before Geofences)
    
    private static final long serialVersionUID = 1L;
    private int id;
    private Device device;
    private String type;
    private Date servertime;
    private Position position;
//    private Integer positionid;
    private Geofence geofence;
//    private Integer geofenceid;
    private String attributes;

    public Event() {
    }

    public Event(int id, String type, Date servertime) {
        this.id = id;
        this.type = type;
        this.servertime = servertime;
    }

    public Event(int id, Device device, String type, Date servertime, 
            Position position, Geofence geofence, String attributes) {
        this.id = id;
        this.device = device;
        this.type = type;
        this.servertime = servertime;
        this.position = position;
        this.geofence = geofence;
//      this.positionid = positionid;
//      this.geofenceid = geofenceid;
        this.attributes = attributes;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="events_id_seq")
    @SequenceGenerator(name="events_id_seq", sequenceName="events_id_seq", allocationSize=1)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid")
    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    @Column(name = "positionid")
    public Position getPosition() {
        return this.position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

//    @Column(name = "positionid")
//    public Integer getPositionid() {
//        return this.positionid; }
//    public void setPositionid(Integer positionid) {
//        this.positionid = positionid; }

    @Column(name = "geofenceid")
    public Geofence getGeofence() {
        return this.geofence;
    }

    public void setGeofence(Geofence geofence) {
        this.geofence = geofence;
    }

//    @Column(name = "geofenceid")
//    public Integer getGeofenceid() {
//        return this.geofenceid; }
//    public void setGeofenceid(Integer geofenceid) {
//        this.geofenceid = geofenceid; }

    @Column(name = "type", nullable = false, length = 128)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "servertime", nullable = false, length = 29)
    public Date getServertime() {
        return this.servertime;
    }

    public void setServertime(Date servertime) {
        this.servertime = servertime;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Override
    public String toString() {
        return "Event [id=" + id + ", device=" + device + ", type=" + type 
                + ", servertime=" + servertime + ", position=" + position 
                + ", geofence=" + geofence + ", attributes=" + attributes 
                + "]";
    }

}
