package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", schema = "public")
public class Groups implements java.io.Serializable {

    private int id;
    private Groups groups;
    private String name;
    private String attributes;
    private Set<Devices> deviceses = new HashSet<Devices>(0);
    private Set<GroupDriver> groupDrivers = new HashSet<GroupDriver>(0);
    private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
    private Set<Groups> groupses = new HashSet<Groups>(0);
    private Set<GroupGeofence> groupGeofences = new HashSet<GroupGeofence>(0);
    private Set<GroupAttribute> groupAttributes = new HashSet<GroupAttribute>(0);

    public Groups() {
    }

    public Groups(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Groups(int id, Groups groups, String name, String attributes, Set<Devices> deviceses,
            Set<GroupDriver> groupDrivers, Set<UserGroup> userGroups, Set<Groups> groupses,
            Set<GroupGeofence> groupGeofences, Set<GroupAttribute> groupAttributes) {
        this.id = id;
        this.groups = groups;
        this.name = name;
        this.attributes = attributes;
        this.deviceses = deviceses;
        this.groupDrivers = groupDrivers;
        this.userGroups = userGroups;
        this.groupses = groupses;
        this.groupGeofences = groupGeofences;
        this.groupAttributes = groupAttributes;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "groupid")
    public Groups getGroups() {
        return this.groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<Devices> getDeviceses() {
        return this.deviceses;
    }

    public void setDeviceses(Set<Devices> deviceses) {
        this.deviceses = deviceses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<GroupDriver> getGroupDrivers() {
        return this.groupDrivers;
    }

    public void setGroupDrivers(Set<GroupDriver> groupDrivers) {
        this.groupDrivers = groupDrivers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<UserGroup> getUserGroups() {
        return this.userGroups;
    }

    public void setUserGroups(Set<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<Groups> getGroupses() {
        return this.groupses;
    }

    public void setGroupses(Set<Groups> groupses) {
        this.groupses = groupses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<GroupGeofence> getGroupGeofences() {
        return this.groupGeofences;
    }

    public void setGroupGeofences(Set<GroupGeofence> groupGeofences) {
        this.groupGeofences = groupGeofences;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    public Set<GroupAttribute> getGroupAttributes() {
        return this.groupAttributes;
    }

    public void setGroupAttributes(Set<GroupAttribute> groupAttributes) {
        this.groupAttributes = groupAttributes;
    }

}
