package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupDriver generated by hbm2java
 */
@Entity
@Table(name = "group_driver", schema = "public")
public class GroupDriver implements java.io.Serializable {

    private GroupDriverId id;
    private Drivers drivers;
    private Groups groups;

    public GroupDriver() {
    }

    public GroupDriver(GroupDriverId id, Drivers drivers, Groups groups) {
        this.id = id;
        this.drivers = drivers;
        this.groups = groups;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)),
            @AttributeOverride(name = "driverid", column = @Column(name = "driverid", nullable = false)) })
    public GroupDriverId getId() {
        return this.id;
    }

    public void setId(GroupDriverId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driverid", nullable = false, insertable = false, updatable = false)
    public Drivers getDrivers() {
        return this.drivers;
    }

    public void setDrivers(Drivers drivers) {
        this.drivers = drivers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "groupid", nullable = false, insertable = false, updatable = false)
    public Groups getGroups() {
        return this.groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

}
