package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupDriverId generated by hbm2java
 */
@Embeddable
public class GroupDriverId implements java.io.Serializable {

    private int groupid;
    private int driverid;

    public GroupDriverId() {
    }

    public GroupDriverId(int groupid, int driverid) {
        this.groupid = groupid;
        this.driverid = driverid;
    }

    @Column(name = "groupid", nullable = false)
    public int getGroupid() {
        return this.groupid;
    }

    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }

    @Column(name = "driverid", nullable = false)
    public int getDriverid() {
        return this.driverid;
    }

    public void setDriverid(int driverid) {
        this.driverid = driverid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof GroupDriverId))
            return false;
        GroupDriverId castOther = (GroupDriverId) other;

        return (this.getGroupid() == castOther.getGroupid()) && (this.getDriverid() == castOther.getDriverid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getGroupid();
        result = 37 * result + this.getDriverid();
        return result;
    }

}
