package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "notifications", schema = "public")
public class Notifications implements java.io.Serializable {

    private int id;
    private Users users;
    private String type;
    private String attributes;
    private Boolean web;
    private Boolean mail;
    private Boolean sms;

    public Notifications() {
    }

    public Notifications(int id, Users users, String type) {
        this.id = id;
        this.users = users;
        this.type = type;
    }

    public Notifications(int id, Users users, String type, String attributes, Boolean web, Boolean mail, Boolean sms) {
        this.id = id;
        this.users = users;
        this.type = type;
        this.attributes = attributes;
        this.web = web;
        this.mail = mail;
        this.sms = sms;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "type", nullable = false, length = 128)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Column(name = "web")
    public Boolean getWeb() {
        return this.web;
    }

    public void setWeb(Boolean web) {
        this.web = web;
    }

    @Column(name = "mail")
    public Boolean getMail() {
        return this.mail;
    }

    public void setMail(Boolean mail) {
        this.mail = mail;
    }

    @Column(name = "sms")
    public Boolean getSms() {
        return this.sms;
    }

    public void setSms(Boolean sms) {
        this.sms = sms;
    }

}
