package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Positions generated by hbm2java
 */
@Entity
@Table(name = "positions", schema = "public")
public class Positions implements java.io.Serializable {

    private int id;
    private Devices devices;
    private String protocol;
    private Date servertime;
    private Date devicetime;
    private Date fixtime;
    private boolean valid;
    private double latitude;
    private double longitude;
    private double altitude;
    private double speed;
    private double course;
    private String address;
    private String attributes;
    private double accuracy;
    private String network;

    public Positions() {
    }

    public Positions(int id, Devices devices, Date servertime, Date devicetime, Date fixtime, boolean valid,
            double latitude, double longitude, double altitude, double speed, double course, double accuracy) {
        this.id = id;
        this.devices = devices;
        this.servertime = servertime;
        this.devicetime = devicetime;
        this.fixtime = fixtime;
        this.valid = valid;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.speed = speed;
        this.course = course;
        this.accuracy = accuracy;
    }

    public Positions(int id, Devices devices, String protocol, Date servertime, Date devicetime, Date fixtime,
            boolean valid, double latitude, double longitude, double altitude, double speed, double course,
            String address, String attributes, double accuracy, String network) {
        this.id = id;
        this.devices = devices;
        this.protocol = protocol;
        this.servertime = servertime;
        this.devicetime = devicetime;
        this.fixtime = fixtime;
        this.valid = valid;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.speed = speed;
        this.course = course;
        this.address = address;
        this.attributes = attributes;
        this.accuracy = accuracy;
        this.network = network;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid", nullable = false)
    public Devices getDevices() {
        return this.devices;
    }

    public void setDevices(Devices devices) {
        this.devices = devices;
    }

    @Column(name = "protocol", length = 128)
    public String getProtocol() {
        return this.protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "servertime", nullable = false, length = 29)
    public Date getServertime() {
        return this.servertime;
    }

    public void setServertime(Date servertime) {
        this.servertime = servertime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "devicetime", nullable = false, length = 29)
    public Date getDevicetime() {
        return this.devicetime;
    }

    public void setDevicetime(Date devicetime) {
        this.devicetime = devicetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fixtime", nullable = false, length = 29)
    public Date getFixtime() {
        return this.fixtime;
    }

    public void setFixtime(Date fixtime) {
        this.fixtime = fixtime;
    }

    @Column(name = "valid", nullable = false)
    public boolean isValid() {
        return this.valid;
    }

    public void setValid(boolean valid) {
        this.valid = valid;
    }

    @Column(name = "latitude", nullable = false, precision = 17, scale = 17)
    public double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "longitude", nullable = false, precision = 17, scale = 17)
    public double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    @Column(name = "altitude", nullable = false, precision = 17, scale = 17)
    public double getAltitude() {
        return this.altitude;
    }

    public void setAltitude(double altitude) {
        this.altitude = altitude;
    }

    @Column(name = "speed", nullable = false, precision = 17, scale = 17)
    public double getSpeed() {
        return this.speed;
    }

    public void setSpeed(double speed) {
        this.speed = speed;
    }

    @Column(name = "course", nullable = false, precision = 17, scale = 17)
    public double getCourse() {
        return this.course;
    }

    public void setCourse(double course) {
        this.course = course;
    }

    @Column(name = "address", length = 512)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Column(name = "accuracy", nullable = false, precision = 17, scale = 17)
    public double getAccuracy() {
        return this.accuracy;
    }

    public void setAccuracy(double accuracy) {
        this.accuracy = accuracy;
    }

    @Column(name = "network", length = 4000)
    public String getNetwork() {
        return this.network;
    }

    public void setNetwork(String network) {
        this.network = network;
    }

}
