package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserUserId generated by hbm2java
 */
@Embeddable
public class UserUserId implements java.io.Serializable {

    private int userid;
    private int manageduserid;

    public UserUserId() {
    }

    public UserUserId(int userid, int manageduserid) {
        this.userid = userid;
        this.manageduserid = manageduserid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "manageduserid", nullable = false)
    public int getManageduserid() {
        return this.manageduserid;
    }

    public void setManageduserid(int manageduserid) {
        this.manageduserid = manageduserid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserUserId))
            return false;
        UserUserId castOther = (UserUserId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getManageduserid() == castOther.getManageduserid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getManageduserid();
        return result;
    }

}
