package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGeofence generated by hbm2java
 */
@Entity
@Table(name = "user_geofence", schema = "public")
public class UserGeofence implements java.io.Serializable {

    private UserGeofenceId id;
    private Geofence geofences;
    private Users users;

    public UserGeofence() {
    }

    public UserGeofence(UserGeofenceId id, Geofence geofences, Users users) {
        this.id = id;
        this.geofences = geofences;
        this.users = users;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "geofenceid", column = @Column(name = "geofenceid", nullable = false)) })
    public UserGeofenceId getId() {
        return this.id;
    }

    public void setId(UserGeofenceId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geofenceid", nullable = false, insertable = false, updatable = false)
    public Geofence getGeofences() {
        return this.geofences;
    }

    public void setGeofences(Geofence geofences) {
        this.geofences = geofences;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
