package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserDeviceId generated by hbm2java
 */
@Embeddable
public class UserDeviceId implements java.io.Serializable {

    private int userid;
    private int deviceid;

    public UserDeviceId() {
    }

    public UserDeviceId(int userid, int deviceid) {
        this.userid = userid;
        this.deviceid = deviceid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "deviceid", nullable = false)
    public int getDeviceid() {
        return this.deviceid;
    }

    public void setDeviceid(int deviceid) {
        this.deviceid = deviceid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserDeviceId))
            return false;
        UserDeviceId castOther = (UserDeviceId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getDeviceid() == castOther.getDeviceid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getDeviceid();
        return result;
    }

}
