package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAttributeId generated by hbm2java
 */
@Embeddable
public class UserAttributeId implements java.io.Serializable {

    private int userid;
    private int attributeid;

    public UserAttributeId() {
    }

    public UserAttributeId(int userid, int attributeid) {
        this.userid = userid;
        this.attributeid = attributeid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "attributeid", nullable = false)
    public int getAttributeid() {
        return this.attributeid;
    }

    public void setAttributeid(int attributeid) {
        this.attributeid = attributeid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserAttributeId))
            return false;
        UserAttributeId castOther = (UserAttributeId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getAttributeid() == castOther.getAttributeid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getAttributeid();
        return result;
    }

}
