package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCalendarId generated by hbm2java
 */
@Embeddable
public class UserCalendarId implements java.io.Serializable {

    private int userid;
    private int calendarid;

    public UserCalendarId() {
    }

    public UserCalendarId(int userid, int calendarid) {
        this.userid = userid;
        this.calendarid = calendarid;
    }

    @Column(name = "userid", nullable = false)
    public int getUserid() {
        return this.userid;
    }

    public void setUserid(int userid) {
        this.userid = userid;
    }

    @Column(name = "calendarid", nullable = false)
    public int getCalendarid() {
        return this.calendarid;
    }

    public void setCalendarid(int calendarid) {
        this.calendarid = calendarid;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserCalendarId))
            return false;
        UserCalendarId castOther = (UserCalendarId) other;

        return (this.getUserid() == castOther.getUserid()) && (this.getCalendarid() == castOther.getCalendarid());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserid();
        result = 37 * result + this.getCalendarid();
        return result;
    }

}
