package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserDevice generated by hbm2java
 */
@Entity
@Table(name = "user_device", schema = "public")
public class UserDevice implements java.io.Serializable {

    private UserDeviceId id;
    private Devices devices;
    private Users users;

    public UserDevice() {
    }

    public UserDevice(UserDeviceId id, Devices devices, Users users) {
        this.id = id;
        this.devices = devices;
        this.users = users;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "deviceid", column = @Column(name = "deviceid", nullable = false)) })
    public UserDeviceId getId() {
        return this.id;
    }

    public void setId(UserDeviceId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deviceid", nullable = false, insertable = false, updatable = false)
    public Devices getDevices() {
        return this.devices;
    }

    public void setDevices(Devices devices) {
        this.devices = devices;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
