[[Building-BuildingCamelfromSource]]

:toc:

= Building JeeTS from Source

[[Building-Prequisites]]
== Prequisites

* Java 1.8

* http://maven.apache.org/download.html[download and install Maven 3.3.3 or newer]

* Get the latest source from https://github.com/kbeigl/jeets/[Github] by running 
[source,text]
-----------------
  git clone https://github.com/kbeigl/jeets.git
-----------------

JeeTS uses http://maven.apache.org/[Maven] as its build and management tool
and the Camel BOM ..
[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-parent</artifactId>
    <version>${camel.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

for versioning the majority of third party software. +
JeeTS versioning should be restricted to 
and maintained in the *jeets-parent/pom.xml*.


[[Building-Anormalbuild]]
== A normal build

The JeeTS repository is combined with multiple 
sub projects/modules (e.g. components, archetypes, tooling etc.). 
Therefore each project is part of the hierarchy it depends on.
Since the JeeTS components are _not_ distributed via Maven Central
each build depends on successful installations of subcomponents.
These subcomponents are not related via folder structure
but they are retrieved from your local Maven repository 
(`M2_REPO` i.e., `~/.m2/repository` on Unix and
`c:\Documents and Settings\<user>\.m2\repository` on Windows) 
which allows the jars to be resolved.

With the well known command line
[source,text]
-----------------
mvn clean install
-----------------
you make sure that the build starts from scratch, retrieves all required
components and installs the subcomponents for later compilation of higher
level components.

[source,text]
-----------------
[INFO] === JeeTS - Java EE Tracking Software   === 1.2.4 .. SUCCESS [  1.393 s]
[INFO] --- JeeTS Parent - global definitions   --- 1.2.4 .. SUCCESS [  0.087 s]
[INFO] --- System Dataformats and Models       --- 1.2.4 .. SUCCESS [  0.121 s]
[INFO] jeets-pu-traccar 4.2 ............................... SUCCESS [ 23.547 s]
[INFO] jeets-pu-gtfs 1.1.1 ................................ SUCCESS [  1.423 s]
[INFO] jeets-protocols 1.2.0 .............................. SUCCESS [  3.391 s]
[INFO] jeets-protocols-traccar 4.8.0316 ................... SUCCESS [01:02 min]
[INFO] --- Client Tracker Components           --- 1.2.4 .. SUCCESS [  0.090 s]
[INFO] jeets-tracker 1.2.3 ................................ SUCCESS [ 14.905 s]
[INFO] jeets-device 1.2.4 ................................. SUCCESS [  8.072 s]
[INFO] jeets-player 1.2.0 ................................. SUCCESS [  0.715 s]
[INFO] my-jeets-client 1.2.3 .............................. SUCCESS [  8.886 s]
[INFO] --- Server Tracking Components (JSE)    --- 1.2.4 .. SUCCESS [  0.094 s]
[INFO] jeets-dcs 1.2.0 .................................... SUCCESS [ 11.265 s]
[INFO] jeets-dcs-traccar 1.2.4 ............................ SUCCESS [ 39.555 s]
[INFO] jeets-etl 1.2.0 .................................... SUCCESS [ 21.659 s]
[INFO] jeets-db-managers 1.2.0 ............................ SUCCESS [ 15.267 s]
[INFO] jeets-dcs-amq 1.2.0 ................................ SUCCESS [ 27.368 s]
[INFO] jeets-geo-router 1.2.0 ............................. SUCCESS [ 16.120 s]
[INFO] --- AppServer Tracking Components (JEE) --- 1.2.0 .. SUCCESS [  0.130 s]
[INFO] jeets-wildfly-activemq-adapter 1.0 ................. SUCCESS [  4.012 s]
[INFO] jeets-jee-app 1.2.0 ................................ SUCCESS [  0.093 s]
[INFO] > jeets-jee-ejb 1.2.0 .............................. SUCCESS [  1.160 s]
[INFO] > jeets-jee-web 1.2.0 .............................. SUCCESS [  2.699 s]
[INFO] > jeets-jee-ear 1.2.0 .............................. SUCCESS [  1.485 s]
[INFO] --- Integration Tests                   --- 1.2.4 .. SUCCESS [  0.235 s]
[INFO] tracker2dcs-itest 1.2.3 ............................ SUCCESS [ 44.626 s]
[INFO] device2protocols-traccar-itest 1.2.4 ............... SUCCESS [ 53.691 s]
[INFO] device2dcs-traccar-itest 1.2.4 ..................... SUCCESS [01:23 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:30 min
[INFO] Finished at: 2020-03-30T12:05:12+02:00
[INFO] ------------------------------------------------------------------------
-----------------

After a successful installation the environment is setup and the 
developer can restrict subsequent builds by going into lower levels
and into the project folders to compile only this one project.

WARNING: Be aware that `SNAPSHOT` releases may be volatile and the repository
         may _not_ compile successful, since the stable releases may not have
         been installed in your local Maven Repository. +
         Please always compile the last major release, 
         before you work with `-SNAPSHOT` versions!

[[Building-Anormalbuildwithoutrunningtests]]
== A build with integration tests

In the above listing you can see the Integration Tests section
which does not show on the normal build and requires the activation
of the Maven Profile *itests*.

The reason is that integration tests can have very long durations
as they can setup the complete system consisting of client, server
and third party software like a Broker, Database or Application server.
Actually Integration Tests can run for hours and are not part of the
every day development process. Developers should take responsibility
to run (relevant) integration tests _before_ they release something.

_After a successful build_ the command line 
[source,text]
-------------------------------
mvn verify -Pitests
-------------------------------
skips the regular unit tests and previous compilations to verify the existence
of the latest artifacts in the `/target` folders of the relevant projects.
Then it runs the integration tests by launching various artifacts 
and now you should see the Integration Tests at the end of the listing 
[source,text]
-----------------
[INFO] --- Integration Tests                   --- 1.2.4 .. SUCCESS [  0.235 s]
[INFO] tracker2dcs-itest 1.2.3 ............................ SUCCESS [ 44.626 s]
[INFO] device2protocols-traccar-itest 1.2.4 ............... SUCCESS [ 53.691 s]
[INFO] device2dcs-traccar-itest 1.2.4 ..................... SUCCESS [01:23 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
-----------------

If you plan to add integration tests it is noteworthy to mention that you _can_
copy filtered resources especially configured for integration testing.


== JeeTS Configuration

The JeeTS repository is a self contained collection of GPS Tracking Software Components
and should always be compiled and tested via Maven runs. 
To use the Components for your own development, staging and production environments
you can copy the `jeets.properties` in the main directory and modify the properties
to your environment variables.

to be continued ... command line options etc.

dynamic variables:

	mvn resources:resources -Djeets.jdbc.url="jdbc:postgresql://localhost:5432/traccar4.1"

Variables can be included in your resources. 
	These variables, denoted by the `${...}` delimiters, 
	can come from the system properties, your project properties, 
	from your filter resources and from the command line.
	
	<!-- replace default settings in repo root (without external path) -->
	mvn initialize -Djeets.properties.file=mycompany.properties 
	mvn clean process-resources   // life-cycle phase
	mvn clean resources:resources //            goal


[[Building-Buildingsourcejars]]
== JeeTS Sources and Javadocs

If you want to build jar files with the source code 
you can run this command from the root folder or from any subfolder
for single project sources.

[source,text]
------------------------------------------
mvn source:jar install
------------------------------------------

You can check your local repo to verify that the `-sources.jar`, +
i.e. `jeets-protocols-traccar-4.2.1-beta-sources.jar`
has been installed.

Creating -javadoc.jars works the same way by entering:

[source,text]
------------------------------------------
mvn javadoc:jar install
------------------------------------------

to create `jeets-pu-traccar-4.2-javadoc.jar` for every project.

[source,text]
------------------------------------------
mvn dependency:resolve -Dclassifier=javadoc
mvn dependency:resolve -Dclassifier=sources
------------------------------------------


// [[Building-Buildingwithcheckstyle]]
// == Building with checkstyle

// To enable source style checking with checkstyle ... TODO

// [source,text]
// -------------------------------
// mvn -Psourcecheck clean install
// -------------------------------

// [[Building-ExecutingunittestsusingEkstazi]]
// == Executing unit tests using Ekstazi

// Normally, when you execute the unit tests during your development cycle
// for a particular component, you are executing all the tests each time.
// This may become inefficient, when you are changing one class and the
// effect of this change is limited within the component having many unit
// tests. Ekstazi is a regression testing tool that can keep track of the
// test results and the changed classes so that unaffected tests can be
// skipped during the subsequent testing. For more details of Ekstazi,
// please refer to the http://www.ekstazi.org[Ekstazi] page.

// To use Ekstazi, you can run the tests with the maven profile ekstazi.

// [source,text]
// ------------------
// mvn test -Pekstazi
// ------------------


