[[jeets-toc]]

:toc:

// IF YOU SEE PLAIN ASCII IN YOUR BROWSER YOU CAN INSTALL 
// THE BROWSER EXTENSION https://asciidoctor.org/
// TO RENDER adoc FILES AND CLICK THE DOCUMENT LINKS.
// (works fine in Firefox, not so fine in Chromecast)


= JeeTS Inline Documentation

This documentation should provide a quick start to run and test the JeeTS repository
and use the compiled artifacts for your own purposes.

== Building the JeeTS Repository

* link:./building.adoc[Building the JeeTS Repository] +
Instructions to compile and test the complete repository.

* link:https://github.com/kbeigl/jeets/issues[JeeTS issue management] +
In case of problems please report issues here.

* link:./ReleaseNotes.adoc[Release Notes] +
major improvements and development steps.

=== Developing JeeTS with Eclipse

* link:./eclipse.adoc[Import JeeTS Repository in Eclipse] +
Instructions to import the complete repository 
or individual projects into Eclipse


== jeets-models

=== The Data Model

The JeeTS repository has emerged from analyzing
the https://github.com/traccar/traccar[Traccar GTS code].
The JeeTS Persistence Unit was coded against the Traccar Model
and as the Standard Model of the JEE JPA specification.

* link:../jeets-models/jeets-pu-traccar/ReadMe.adoc[jeets-pu-traccar] +
represents the Traccar Entity Relation Model specified 
with a JPA Persistence Unit and related Java Entities.


=== GPS Protocols

The System Data Model actually defines all pieces of information
a Tracking System can accept and process. 
GPS messages form 'sentences' encoded by a dedicated protocol
to be sent to the system. 
The *jeets-protocols* project is supplying Protobuffers 
for effective binary encoding and decoding.

* link:../jeets-models/jeets-protocols/ReadMe.adoc[jeets-protocols] +
adds Protocol Buffers to send Traccar Messages in binary format. 


== jeets-clients

=== Simulate Trackers

When developing GPS Tracking Components it can be very helpful  
to send messages as needed. 
This is exactly what the JeeTS Tracker Software was created for:

* link:../jeets-clients/jeets-tracker/README.adoc[jeets-tracker] +
is a simple client software to send messages to a specified host 
and port. Developers should find it easy to adopt this 'sender'
to their requirements.


== jeets-server-jse

The *jeets-server* folders are holding the server components
to compose a Tracking System according to your needs.
The *jeets-server-jse* components are build with the Java Standard 
Edition combined with various Frameworks and can be launched
from command line.

=== Device Communication

The core of a GPS Tracking System is the reception of encoded protocol data
and the decoding and transformation to a general System Data Format,
being JPA Entities aligned with the Data/base Model.
The complete process is usually referred to as Device Communication 
and each Protocol has one or more Device Communication Server.

==== Creating a Device Communication Server

In order to grasp the JeeTS modeling process from the monolithic 
Traccar GTS to individual components you can look 
at the following projects consecutively:

* link:../jeets-server-jse/jeets-dcs/ReadMe.adoc[jeets-dcs] +
combines the above projects (pu and protocols) to receive binary 
Protobuffer messages and transform them to Java Entities.


=== Running Traccar Device Communication Servers

After you have grasped the cascaded approach you can proceed
to build the stand alone application *jeets-dcs-traccar.jar* 
to receive Tracker Messages from any Tracker supported by Traccar!
The cascaded build works analog to the example above
only with more complex modules:

. link:../jeets-models/jeets-pu-traccar/ReadMe.adoc[jeets-pu-traccar]
as above

. link:../jeets-models/jeets-protocols-traccar/jeets-protocols-traccar.adoc[jeets-protocols-traccar] +
provides all protocols from the (main releases of) Traccar GTS 

. link:../jeets-server-jse/jeets-dcs-traccar/ReadMe.adoc[jeets-dcs-traccar] +
combines the above projects to receive messages from any Tracker
supported by Traccar protocol implementations.
The application applies the Camel Framework to create Routes 
from each protocol port to a unified output of Traccar Entities.

WARNING: The *jeets-dcs-traccar* project is still in experimental
         beta stage. Upcoming main releases v4.x will improve
         this component to a stand alone DCS manager.


== jeets-itests

This folder is providing an *Integration Test* environment to setup 
and test different components close to a production environment.


=== Testing Device Communication

The *tracker2dcs* integration test sets up the *jeets-dcs*, 
which includes the projects *jeets-pu-traccar* and *jeets-protocols*
to receive Traccar Protobuffers.

Then it starts the *jeets-tracker*, which also includes 
the projects *jeets-pu-traccar* and *jeets-protocols*,
to send Traccar Protobuffers.

* link:../jeets-itests/tracker2dcs/ReadMe.adoc[tracker2dcs] +
By studying this integration test you can find out how to send
messages from a client to a server and assert their communication.







