[[jeets-toc]]

:toc:

// IF YOU SEE PLAIN ASCII IN YOUR BROWSER YOU CAN INSTALL 
// THE BROWSER EXTENSION https://asciidoctor.org/
// TO RENDER adoc FILES AND CLICK THE DOCUMENT LINKS.
// (works fine in Firefox, not so fine in Chromecast)


= JeeTS Inline Documentation

This documentation provides a Quick Start to run and test the JeeTS repository +
and use the compiled JeeTS artifacts for your own projects.

== jeets-models

=== The Data Model

The JeeTS repository has emerged from analyzing
the https://github.com/traccar/traccar[Traccar GTS code].
The JeeTS Persistence Unit was coded against the Traccar Model
and as the Standard Model of the JEE JPA specification.

* link:../jeets-models/jeets-pu-traccar/README.adoc[jeets-pu-traccar] +
represents the Traccar Entity Relation Model specified 
with a JPA Persistence Unit and related Java *System Entities*.


=== GPS Protocols

The System Data Model defines all pieces of information
a Tracking System can accept and process. 
GPS messages form 'sentences' encoded by a dedicated protocol
to be sent to the system. 

* link:../jeets-models/jeets-protocols-traccar/jeets-protocols-traccar.adoc[jeets-protocols-traccar] +
is derived from Traccar and isolates the link:www.traccar.org/protocols/[Traccar Protocols]
into a single Java Jar, which can be used for your own Tracking Projects to receive 
a single Java Entity Format from all link:https://www.traccar.org/devices/[Devices supported by Traccar].
The JeeTS project supplies a single Endpoint where you can pick up all incoming messages
to process them however you please. Apply any 
link:https://www.enterpriseintegrationpatterns.com/patterns/messaging/toc.html[Enterprise Integration Pattern] 
to hook up your own system easily.

* link:../jeets-models/jeets-protocols/README.adoc[jeets-protocols] +
is a project to define any GPS Protocol and run it in conjunction with JeeTS components. 
Protocols can be implemented 'the Traccar way', compiled together with - and into - 
the jeets-protocols-traccar project. 
You can also define your own protocols with Netty, add a Camel Endpoint 
and run them in a Spring Framework or whatever is appropriate for you.


== jeets-clients

=== Simulate Trackers

When developing GPS Tracking Components it can be very helpful  
to send messages as needed. 
This is exactly what the JeeTS Tracker Software was created for:

* jeets-tracker was removed to be replace with the .. +

* link:../jeets-clients/jeets-device/README.adoc[jeets-device] +
is the successor of the jeets-tracker applying Camel's Producer 
Template to send byte or hex messages and collect the response.



== jeets-server-etl

*ETL Components* are important entry points to standardize a system.

They *Extract, Transform and Load* Data to other JeeTS Components.
*Device Communication Servers* receive encoded data from the network, 
*Extract* the proprietary format, 
*Transform* it into a standard *System Entity* and 
finally *Loaders* load it to a Database, a Message Broker or any existing resource.

=== Device Communication

The core of a GPS Tracking System is the reception of encoded protocol data
and the decoding and transformation to a general System Data Format,
like JPA Entities aligned with the Data/base Model.
The complete process is usually referred to as Device Communication 
and each Protocol has one or more *Device Communication Servers*.


=== Managing DC Servers

The link:../jeets-server-etl/jeets-dcs-manager/ReadMe.adoc[*jeets-dcs-manager*] 
is a stand alone application to run a large number
of Device Communication Servers. You can run all Traccar Protocols out of the box,
add your own protocol implementations with Netty Standard En/Decoders.

The DCS Manager combines existing protocols and DC Servers to collect
all of their data at a single Consumer Endpoint. 
A pure Spring Application controlled by SpringBoot- and Netty Starters! 

TODOcument

. link:../jeets-server-etl/jeets-etl/[*jeets-etl*]

. link:../jeets-server-etl/my-etl-traccar/[*my-etl-traccar*]

. link:../jeets-server-etl/jeets-dcs-amq/[*jeets-dcs-amq*]

. and more Loaders and ETL Modules ...


== jeets-server-jse

The *jeets-server-jse* folder is holding the server components
to compose a Tracking System according to your needs.
The components are build with the Java Standard 
Edition combined with various Frameworks and can be launched
from command line.


== jeets-server-jee ..

was depecated removed. +
Please let us know if you require Application Server code.


== jeets-itests

This folder is providing an 
link:../jeets-itests/README.adoc[Integration Test] 
environment to setup and test different components 
close to a production environment.


// === Testing Device Communication

// The *tracker2dcs* integration test sets up the *jeets-dcs*, 
// which includes the projects *jeets-pu-traccar* and *jeets-protocols*
// to receive Traccar Protobuffers.

// Then it starts the *jeets-tracker*, which also includes 
// the projects *jeets-pu-traccar* and *jeets-protocols*,
// to send Traccar Protobuffers.
