
:toc:

= Release Notes - JeeTS repository

=== 2021 Jan - v1.3.1

* updated Device Communication Servers for all Traccar Protocols! +
** `jeets-protocols-traccar 4.11` 
*** added Map to distinguish UDP from TCP protocol transport
** `jeets-dcs-manager 1.3.1` 

 * Repository development and build with *Java-11*-OpenJDK-11.0.8-1 under Windows 10 :
 
[source,text]
-----------------
> mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\prox\Maven\apache-maven-3.6.0
Java version: 11.0.8, vendor: ojdkbuild, runtime: C:\prox\OpenJDK\ojdkbuild\java-11-openjdk-11.0.8-1
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
	
> mvn <goals>
[INFO] Detecting the operating system and CPU architecture
[INFO] ---------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO] ---------------------------------------------------
-----------------

Note that most projects are still running with backward compatible compiler settings 
which will be curated as we move on.

* removed projects that will be replaced by the `jeets-device` project
** `jeets-tracker` - plain java tracker
** `my-jeets-client` - client artifact to create a client with a built in tracker

* Introduced Google Code Format/ter (in some projects)



=== 2020 Aug - v1.3

* `jeets-protocols` +
** automated generation of ProtoBuffers from *.proto files in Maven build +
** implemented jeets.proto/buffers as _the_ JeeTS Protocol +
   compatible to Traccar Database Model, i.e. ERM
** currently depends on `jeets-protocols-traccar` +
   to enable compiling additional protocols in Traccar style

* generalized `jeets-dcs-traccar` to `jeets-dcs-manager` +
** includes `jeets-protocols` with additional / alternate protocols to Traccar protocols
*** includes `jeets-pu-traccar`
*** and `jeets-protocols-traccar`

* added `my-etl-traccar` 
for Maven Archetype generation of custom Traccar ETL MicroService

* moved all project data to jeets-data folder +
 applied variable replacement for traccar/setup folder 

* Camel Migration 2.24.x to 3.3.0

* restructured repository 
** added explicit ETL section to Extract Transform & Load Data
** detached JEE section for application server support
   Please read 
   link:../jeets-server-jee/ReadMe.adoc#Support[this], if you are affected. 



=== 2020 Mar - v1.2.4

* updated Device Communication Servers for all Traccar Protocols! +
** `jeets-protocols-traccar 4.8.0316` 

* re-engineered `jeets-dcs-traccar` as Spring Boot Microservice
** includes `jeets-protocols-traccar`

* improved `jeets-device` as development and testing tool

* added `jeets-data` folder for sample data, testing and development of JeeTS components 

* added Integration Tests `device2protocols-traccar-itest` and `device2dcs-traccar-itest` + 
  to send messages via `jeets-device` and receive messages +
** `jeets-protocols-traccar` to test the original Traccar protocols +
** `jeets-protocols-dcs` to test Traccar protocols as Spring Boot Microservice


=== 2020 Jan - v1.2.3

* added `jeets-device` as successor of jeets-tracker

* updated Device Communication Servers for all Traccar Protocols! +
** `jeets-dcs-traccar 4.6-191229` 
** includes `jeets-protocols-traccar 4.6-191229`
** includes `jeets-pu-traccar 4.2` +
   v4.1 = v4.2 = v4.3

* added Integration Test to send messages via jeets-device +
  and receive messages with jeets-protocols-traccar

* added `org.springframework.boot` BOM before Camel BOM +
to reduce explicit versioning for postgres etc. .. ongoing


=== 2019 May - v1.2.2

* updated Device Communication Servers for all Traccar Protocols! +
For details goto the link:../jeets-server-jse/jeets-dcs-traccar/ReadMe.adoc[project's readme file]
** `jeets-dcs-traccar 4.3.0-beta` 
** includes `jeets-protocols-traccar 4.3.0-beta`
** includes `jeets-pu-traccar 4.2` +
   v4.1 = v4.2 = v4.3
   
* Upgraded Camel from 2.20.2 to 2.24.0
  with issues 
  #2 google API key required bug
  #3 org.xml.sax.SAXParseException bug


=== 2019 Mar - v1.2.1

* Device Communication Servers for all Traccar Protocols! +
For details goto the link:../jeets-server-jse/jeets-dcs-traccar/ReadMe.adoc[project's readme file]
** `jeets-dcs-traccar 4.2.3-beta` 
** includes `jeets-protocols-traccar 4.2.3-beta`
** includes `jeets-pu-traccar 4.2`


=== 2018 Dec - v1.2.0

* update `jeets-pu-traccar` _complete repository_ to v4.2	!
* original traccar ERM 4.1 was _not_ modified for Traccar 4.2 +
  therefore `jeets-pu-traccar` v4.1 = v4.2


=== 2018 Nov - v1.1.1

* update `jeets-pu-traccar` to 4.2
* update `jeets-pu-traccar` to 4.1 +
  complete new Entities, full ORM model!, new EntityManagerTest, 
		removed deprecated tests 
* added `sql-maven-plugin` to drop and create database via scripts

==== known issue

* pu 4.1 is isolated and not upgraded for complete repo +
  repo is not consistent, 
  since required version 3.14 is not pre-compiled

=== 2018 Nov - v1.1.0

* added `jeets.properties` to configure complete repo and tests +
  `jeets-pu-traccar-jpa` is fully configurable

* added integration-tests branch with
	** `itests` folder with aggregate pom for itests modules
	** maven-directory-plugin
	** maven-failsafe-plugin
	** maven-property-plugin
	** maven-resources-plugin with filtering of project properties
	** `<profile><id>itests</id>` +
	sample project tracker with itest `tracker2dcs` +
	tracker is launched with `-props` (default props in jar)

* reduced projects and folders:
	** removed `jeets-pu-traccar-hibernate` +
	   which was only created as an example in the book
	** removed `jeets-pu-traccar-ejb` +
	   which was only a skeleton created from a wizard
	** removed `jeets-pu-traccar-jee` 
	** united  `jeets-pu-traccar-jpa` initially for standard Java JSE +
       with `jeets-pu-traccar-jee` modified for WildFly JEE `jta-data-source` 
       in `jeets-pu-traccar-jpa` version 3.14.3 +
       two persistence units jpa and jee in one `persistence.xml`!

=== 2018 Aug - v1.0-Final

This is the version developed during writing of the book.
The Final release is cleaned from some issues 
and is the JeeTS version recommended for developers 
learning Jee development with GPS Tracking.




