
= JeeTS Integration Tests

The itests, i.e. JeeTS integration tests directory, can be run to test various
JeeTS components against each other. This directory should 
not include Unit Testing, which can be found in each individual component project.


== Usage

All tests, i.e. Unit and Integration tests can be launched for the complete repo. +
Without the itests profile only JUnit tests are executed:

    ...\github.jeets>
	mvn test   -> surefire Unit for all aggregates (models, clients, ... )
	mvn verify -> surefire Unit tests just like mvn test
	
With the itests profile only Integration tests are executed:
	
	mvn test   -Pitests	 -> skips all  tests
	mvn verify -Pitests	 -> skips Unit tests, run integration tests

In order to keep it this way all aggregates - except itests - 
should only implement Unit tests only itests should implement integration tests 
to test JeeTS components against each other and should not implement Unit tests.


== Integration Development

Integration Tests can be very useful at development time in order to run 
different components together and keep the repository consistent.

Please check out this link:./device2protocols-traccar/README.adoc[sample integration test] for details.




## License

    Apache License, Version 2.0
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
