package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attributes generated by hbm2java
 */
@Entity
@Table(name = "attributes", schema = "public")
public class Attributes implements java.io.Serializable {

    private int id;
    private String description;
    private String type;
    private String attribute;
    private String expression;
    private Set<DeviceAttribute> deviceAttributes = new HashSet<DeviceAttribute>(0);
    private Set<GroupAttribute> groupAttributes = new HashSet<GroupAttribute>(0);
    private Set<UserAttribute> userAttributes = new HashSet<UserAttribute>(0);

    public Attributes() {
    }

    public Attributes(int id, String description, String type, String attribute, String expression) {
        this.id = id;
        this.description = description;
        this.type = type;
        this.attribute = attribute;
        this.expression = expression;
    }

    public Attributes(int id, String description, String type, String attribute, String expression,
            Set<DeviceAttribute> deviceAttributes, Set<GroupAttribute> groupAttributes,
            Set<UserAttribute> userAttributes) {
        this.id = id;
        this.description = description;
        this.type = type;
        this.attribute = attribute;
        this.expression = expression;
        this.deviceAttributes = deviceAttributes;
        this.groupAttributes = groupAttributes;
        this.userAttributes = userAttributes;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "description", nullable = false, length = 4000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "type", nullable = false, length = 128)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "attribute", nullable = false, length = 128)
    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    @Column(name = "expression", nullable = false, length = 4000)
    public String getExpression() {
        return this.expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<DeviceAttribute> getDeviceAttributes() {
        return this.deviceAttributes;
    }

    public void setDeviceAttributes(Set<DeviceAttribute> deviceAttributes) {
        this.deviceAttributes = deviceAttributes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<GroupAttribute> getGroupAttributes() {
        return this.groupAttributes;
    }

    public void setGroupAttributes(Set<GroupAttribute> groupAttributes) {
        this.groupAttributes = groupAttributes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<UserAttribute> getUserAttributes() {
        return this.userAttributes;
    }

    public void setUserAttributes(Set<UserAttribute> userAttributes) {
        this.userAttributes = userAttributes;
    }

}
