package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servers generated by hbm2java
 */
@Entity
@Table(name = "servers", schema = "public")
public class Servers implements java.io.Serializable {

    private int id;
    private boolean registration;
    private double latitude;
    private double longitude;
    private int zoom;
    private String map;
    private String bingkey;
    private String mapurl;
    private boolean readonly;
    private boolean twelvehourformat;
    private String attributes;
    private boolean forcesettings;
    private String coordinateformat;
    private Boolean devicereadonly;

    public Servers() {
    }

    public Servers(int id, boolean registration, double latitude, double longitude, int zoom, boolean readonly,
            boolean twelvehourformat, boolean forcesettings) {
        this.id = id;
        this.registration = registration;
        this.latitude = latitude;
        this.longitude = longitude;
        this.zoom = zoom;
        this.readonly = readonly;
        this.twelvehourformat = twelvehourformat;
        this.forcesettings = forcesettings;
    }

    public Servers(int id, boolean registration, double latitude, double longitude, int zoom, String map,
            String bingkey, String mapurl, boolean readonly, boolean twelvehourformat, String attributes,
            boolean forcesettings, String coordinateformat, Boolean devicereadonly) {
        this.id = id;
        this.registration = registration;
        this.latitude = latitude;
        this.longitude = longitude;
        this.zoom = zoom;
        this.map = map;
        this.bingkey = bingkey;
        this.mapurl = mapurl;
        this.readonly = readonly;
        this.twelvehourformat = twelvehourformat;
        this.attributes = attributes;
        this.forcesettings = forcesettings;
        this.coordinateformat = coordinateformat;
        this.devicereadonly = devicereadonly;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "registration", nullable = false)
    public boolean isRegistration() {
        return this.registration;
    }

    public void setRegistration(boolean registration) {
        this.registration = registration;
    }

    @Column(name = "latitude", nullable = false, precision = 17, scale = 17)
    public double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "longitude", nullable = false, precision = 17, scale = 17)
    public double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    @Column(name = "zoom", nullable = false)
    public int getZoom() {
        return this.zoom;
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

    @Column(name = "map", length = 128)
    public String getMap() {
        return this.map;
    }

    public void setMap(String map) {
        this.map = map;
    }

    @Column(name = "bingkey", length = 128)
    public String getBingkey() {
        return this.bingkey;
    }

    public void setBingkey(String bingkey) {
        this.bingkey = bingkey;
    }

    @Column(name = "mapurl", length = 512)
    public String getMapurl() {
        return this.mapurl;
    }

    public void setMapurl(String mapurl) {
        this.mapurl = mapurl;
    }

    @Column(name = "readonly", nullable = false)
    public boolean isReadonly() {
        return this.readonly;
    }

    public void setReadonly(boolean readonly) {
        this.readonly = readonly;
    }

    @Column(name = "twelvehourformat", nullable = false)
    public boolean isTwelvehourformat() {
        return this.twelvehourformat;
    }

    public void setTwelvehourformat(boolean twelvehourformat) {
        this.twelvehourformat = twelvehourformat;
    }

    @Column(name = "attributes", length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Column(name = "forcesettings", nullable = false)
    public boolean isForcesettings() {
        return this.forcesettings;
    }

    public void setForcesettings(boolean forcesettings) {
        this.forcesettings = forcesettings;
    }

    @Column(name = "coordinateformat", length = 128)
    public String getCoordinateformat() {
        return this.coordinateformat;
    }

    public void setCoordinateformat(String coordinateformat) {
        this.coordinateformat = coordinateformat;
    }

    @Column(name = "devicereadonly")
    public Boolean getDevicereadonly() {
        return this.devicereadonly;
    }

    public void setDevicereadonly(Boolean devicereadonly) {
        this.devicereadonly = devicereadonly;
    }

}
