package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statistics generated by hbm2java
 */
@Entity
@Table(name = "statistics", schema = "public")
public class Statistics implements java.io.Serializable {

    private int id;
    private Date capturetime;
    private int activeusers;
    private int activedevices;
    private int requests;
    private int messagesreceived;
    private int messagesstored;
    private String attributes;
    private int mailsent;
    private int smssent;
    private int geocoderrequests;
    private int geolocationrequests;

    public Statistics() {
    }

    public Statistics(int id, Date capturetime, int activeusers, int activedevices, int requests, int messagesreceived,
            int messagesstored, String attributes, int mailsent, int smssent, int geocoderrequests,
            int geolocationrequests) {
        this.id = id;
        this.capturetime = capturetime;
        this.activeusers = activeusers;
        this.activedevices = activedevices;
        this.requests = requests;
        this.messagesreceived = messagesreceived;
        this.messagesstored = messagesstored;
        this.attributes = attributes;
        this.mailsent = mailsent;
        this.smssent = smssent;
        this.geocoderrequests = geocoderrequests;
        this.geolocationrequests = geolocationrequests;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "capturetime", nullable = false, length = 29)
    public Date getCapturetime() {
        return this.capturetime;
    }

    public void setCapturetime(Date capturetime) {
        this.capturetime = capturetime;
    }

    @Column(name = "activeusers", nullable = false)
    public int getActiveusers() {
        return this.activeusers;
    }

    public void setActiveusers(int activeusers) {
        this.activeusers = activeusers;
    }

    @Column(name = "activedevices", nullable = false)
    public int getActivedevices() {
        return this.activedevices;
    }

    public void setActivedevices(int activedevices) {
        this.activedevices = activedevices;
    }

    @Column(name = "requests", nullable = false)
    public int getRequests() {
        return this.requests;
    }

    public void setRequests(int requests) {
        this.requests = requests;
    }

    @Column(name = "messagesreceived", nullable = false)
    public int getMessagesreceived() {
        return this.messagesreceived;
    }

    public void setMessagesreceived(int messagesreceived) {
        this.messagesreceived = messagesreceived;
    }

    @Column(name = "messagesstored", nullable = false)
    public int getMessagesstored() {
        return this.messagesstored;
    }

    public void setMessagesstored(int messagesstored) {
        this.messagesstored = messagesstored;
    }

    @Column(name = "attributes", nullable = false, length = 4000)
    public String getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    @Column(name = "mailsent", nullable = false)
    public int getMailsent() {
        return this.mailsent;
    }

    public void setMailsent(int mailsent) {
        this.mailsent = mailsent;
    }

    @Column(name = "smssent", nullable = false)
    public int getSmssent() {
        return this.smssent;
    }

    public void setSmssent(int smssent) {
        this.smssent = smssent;
    }

    @Column(name = "geocoderrequests", nullable = false)
    public int getGeocoderrequests() {
        return this.geocoderrequests;
    }

    public void setGeocoderrequests(int geocoderrequests) {
        this.geocoderrequests = geocoderrequests;
    }

    @Column(name = "geolocationrequests", nullable = false)
    public int getGeolocationrequests() {
        return this.geolocationrequests;
    }

    public void setGeolocationrequests(int geolocationrequests) {
        this.geolocationrequests = geolocationrequests;
    }

}
