package org.jeets.model.traccar.jpa;
// Generated 15.09.2017 14:36:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserUser generated by hbm2java
 */
@Entity
@Table(name = "user_user", schema = "public")
public class UserUser implements java.io.Serializable {

    private UserUserId id;
    private Users usersByUserid;
    private Users usersByManageduserid;

    public UserUser() {
    }

    public UserUser(UserUserId id, Users usersByUserid, Users usersByManageduserid) {
        this.id = id;
        this.usersByUserid = usersByUserid;
        this.usersByManageduserid = usersByManageduserid;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
            @AttributeOverride(name = "manageduserid", column = @Column(name = "manageduserid", nullable = false)) })
    public UserUserId getId() {
        return this.id;
    }

    public void setId(UserUserId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
    public Users getUsersByUserid() {
        return this.usersByUserid;
    }

    public void setUsersByUserid(Users usersByUserid) {
        this.usersByUserid = usersByUserid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manageduserid", nullable = false, insertable = false, updatable = false)
    public Users getUsersByManageduserid() {
        return this.usersByManageduserid;
    }

    public void setUsersByManageduserid(Users usersByManageduserid) {
        this.usersByManageduserid = usersByManageduserid;
    }

}
