package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * AttributeAliases generated by hbm2java
 */
public class AttributeAliases implements java.io.Serializable {

	private int id;
	private Devices devices;
	private String attribute;
	private String alias;

	public AttributeAliases() {
	}

	public AttributeAliases(int id, Devices devices, String attribute, String alias) {
		this.id = id;
		this.devices = devices;
		this.attribute = attribute;
		this.alias = alias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
