package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Geofences generated by hbm2java
 */
public class Geofences implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String area;
	private String attributes;
	private Set<GroupGeofence> groupGeofences = new HashSet<GroupGeofence>(0);
	private Set<UserGeofence> userGeofences = new HashSet<UserGeofence>(0);
	private Set<DeviceGeofence> deviceGeofences = new HashSet<DeviceGeofence>(0);

	public Geofences() {
	}

	public Geofences(int id, String name, String area, String attributes) {
		this.id = id;
		this.name = name;
		this.area = area;
		this.attributes = attributes;
	}

	public Geofences(int id, String name, String description, String area, String attributes,
			Set<GroupGeofence> groupGeofences, Set<UserGeofence> userGeofences, Set<DeviceGeofence> deviceGeofences) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.area = area;
		this.attributes = attributes;
		this.groupGeofences = groupGeofences;
		this.userGeofences = userGeofences;
		this.deviceGeofences = deviceGeofences;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public Set<GroupGeofence> getGroupGeofences() {
		return this.groupGeofences;
	}

	public void setGroupGeofences(Set<GroupGeofence> groupGeofences) {
		this.groupGeofences = groupGeofences;
	}

	public Set<UserGeofence> getUserGeofences() {
		return this.userGeofences;
	}

	public void setUserGeofences(Set<UserGeofence> userGeofences) {
		this.userGeofences = userGeofences;
	}

	public Set<DeviceGeofence> getDeviceGeofences() {
		return this.deviceGeofences;
	}

	public void setDeviceGeofences(Set<DeviceGeofence> deviceGeofences) {
		this.deviceGeofences = deviceGeofences;
	}

}
