package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * GroupGeofenceId generated by hbm2java
 */
public class GroupGeofenceId implements java.io.Serializable {

	private int groupid;
	private int geofenceid;

	public GroupGeofenceId() {
	}

	public GroupGeofenceId(int groupid, int geofenceid) {
		this.groupid = groupid;
		this.geofenceid = geofenceid;
	}

	public int getGroupid() {
		return this.groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

	public int getGeofenceid() {
		return this.geofenceid;
	}

	public void setGeofenceid(int geofenceid) {
		this.geofenceid = geofenceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupGeofenceId))
			return false;
		GroupGeofenceId castOther = (GroupGeofenceId) other;

		return (this.getGroupid() == castOther.getGroupid()) && (this.getGeofenceid() == castOther.getGeofenceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupid();
		result = 37 * result + this.getGeofenceid();
		return result;
	}

}
