package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Statistics generated by hbm2java
 */
public class Statistics implements java.io.Serializable {

	private int id;
	private Date capturetime;
	private int activeusers;
	private int activedevices;
	private int requests;
	private int messagesreceived;
	private int messagesstored;
	private String attributes;

	public Statistics() {
	}

	public Statistics(int id, Date capturetime, int activeusers, int activedevices, int requests, int messagesreceived,
			int messagesstored, String attributes) {
		this.id = id;
		this.capturetime = capturetime;
		this.activeusers = activeusers;
		this.activedevices = activedevices;
		this.requests = requests;
		this.messagesreceived = messagesreceived;
		this.messagesstored = messagesstored;
		this.attributes = attributes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCapturetime() {
		return this.capturetime;
	}

	public void setCapturetime(Date capturetime) {
		this.capturetime = capturetime;
	}

	public int getActiveusers() {
		return this.activeusers;
	}

	public void setActiveusers(int activeusers) {
		this.activeusers = activeusers;
	}

	public int getActivedevices() {
		return this.activedevices;
	}

	public void setActivedevices(int activedevices) {
		this.activedevices = activedevices;
	}

	public int getRequests() {
		return this.requests;
	}

	public void setRequests(int requests) {
		this.requests = requests;
	}

	public int getMessagesreceived() {
		return this.messagesreceived;
	}

	public void setMessagesreceived(int messagesreceived) {
		this.messagesreceived = messagesreceived;
	}

	public int getMessagesstored() {
		return this.messagesstored;
	}

	public void setMessagesstored(int messagesstored) {
		this.messagesstored = messagesstored;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

}
