package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private String name;
	private String email;
	private String hashedpassword;
	private String salt;
	private boolean readonly;
	private boolean admin;
	private String map;
	private String distanceunit;
	private String speedunit;
	private double latitude;
	private double longitude;
	private int zoom;
	private boolean twelvehourformat;
	private String attributes;
	private String coordinateformat;
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
	private Set<Notifications> notificationses = new HashSet<Notifications>(0);
	private Set<UserDevice> userDevices = new HashSet<UserDevice>(0);
	private Set<UserGeofence> userGeofences = new HashSet<UserGeofence>(0);

	public Users() {
	}

	public Users(int id, String name, String email, String hashedpassword, String salt, boolean readonly, boolean admin,
			double latitude, double longitude, int zoom, boolean twelvehourformat) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.hashedpassword = hashedpassword;
		this.salt = salt;
		this.readonly = readonly;
		this.admin = admin;
		this.latitude = latitude;
		this.longitude = longitude;
		this.zoom = zoom;
		this.twelvehourformat = twelvehourformat;
	}

	public Users(int id, String name, String email, String hashedpassword, String salt, boolean readonly, boolean admin,
			String map, String distanceunit, String speedunit, double latitude, double longitude, int zoom,
			boolean twelvehourformat, String attributes, String coordinateformat, Set<UserGroup> userGroups,
			Set<Notifications> notificationses, Set<UserDevice> userDevices, Set<UserGeofence> userGeofences) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.hashedpassword = hashedpassword;
		this.salt = salt;
		this.readonly = readonly;
		this.admin = admin;
		this.map = map;
		this.distanceunit = distanceunit;
		this.speedunit = speedunit;
		this.latitude = latitude;
		this.longitude = longitude;
		this.zoom = zoom;
		this.twelvehourformat = twelvehourformat;
		this.attributes = attributes;
		this.coordinateformat = coordinateformat;
		this.userGroups = userGroups;
		this.notificationses = notificationses;
		this.userDevices = userDevices;
		this.userGeofences = userGeofences;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHashedpassword() {
		return this.hashedpassword;
	}

	public void setHashedpassword(String hashedpassword) {
		this.hashedpassword = hashedpassword;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public boolean isReadonly() {
		return this.readonly;
	}

	public void setReadonly(boolean readonly) {
		this.readonly = readonly;
	}

	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public String getMap() {
		return this.map;
	}

	public void setMap(String map) {
		this.map = map;
	}

	public String getDistanceunit() {
		return this.distanceunit;
	}

	public void setDistanceunit(String distanceunit) {
		this.distanceunit = distanceunit;
	}

	public String getSpeedunit() {
		return this.speedunit;
	}

	public void setSpeedunit(String speedunit) {
		this.speedunit = speedunit;
	}

	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public int getZoom() {
		return this.zoom;
	}

	public void setZoom(int zoom) {
		this.zoom = zoom;
	}

	public boolean isTwelvehourformat() {
		return this.twelvehourformat;
	}

	public void setTwelvehourformat(boolean twelvehourformat) {
		this.twelvehourformat = twelvehourformat;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public String getCoordinateformat() {
		return this.coordinateformat;
	}

	public void setCoordinateformat(String coordinateformat) {
		this.coordinateformat = coordinateformat;
	}

	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}

	public Set<Notifications> getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set<Notifications> notificationses) {
		this.notificationses = notificationses;
	}

	public Set<UserDevice> getUserDevices() {
		return this.userDevices;
	}

	public void setUserDevices(Set<UserDevice> userDevices) {
		this.userDevices = userDevices;
	}

	public Set<UserGeofence> getUserGeofences() {
		return this.userGeofences;
	}

	public void setUserGeofences(Set<UserGeofence> userGeofences) {
		this.userGeofences = userGeofences;
	}

}
