package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserGeofenceId generated by hbm2java
 */
public class UserGeofenceId implements java.io.Serializable {

	private int userid;
	private int geofenceid;

	public UserGeofenceId() {
	}

	public UserGeofenceId(int userid, int geofenceid) {
		this.userid = userid;
		this.geofenceid = geofenceid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getGeofenceid() {
		return this.geofenceid;
	}

	public void setGeofenceid(int geofenceid) {
		this.geofenceid = geofenceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGeofenceId))
			return false;
		UserGeofenceId castOther = (UserGeofenceId) other;

		return (this.getUserid() == castOther.getUserid()) && (this.getGeofenceid() == castOther.getGeofenceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getGeofenceid();
		return result;
	}

}
