package org.jeets.model.traccar.hibernate;
// Generated 26.11.2016 13:04:29 by Hibernate Tools 5.2.0.Beta1

/**
 * UserDevice generated by hbm2java
 */
public class UserDevice implements java.io.Serializable {

	private UserDeviceId id;
	private Devices devices;
	private Users users;

	public UserDevice() {
	}

	public UserDevice(UserDeviceId id, Devices devices, Users users) {
		this.id = id;
		this.devices = devices;
		this.users = users;
	}

	public UserDeviceId getId() {
		return this.id;
	}

	public void setId(UserDeviceId id) {
		this.id = id;
	}

	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
