
:toc:


[[jeets-protocols-traccar]]
= JeeTS-protocols-traccar

This project is a stripped down version of the http://traccar.org[Traccar GTS] 
i.e. Traccar light, to run the Device Communication Servers (DCS) exclusively.
All DCS servers provide the same output format being 
the `org.traccar.model.Position` java class.

== overview

The main effort of the code reduction was to conserve the original 
`org.traccar.protocol` package for regression tests etc. 
Please consult traccar.org for protocol details. 
Anton Tananaev is doing an incredible job maintaining
about 200 protocols on a daily basis.

The main purpose of this project is to provide all Traccar protocols for your own Tracking Application.
The `jeets-dcs` project demos how to use the protocols with the Spring/Boot/Starter- and Camel Frameworks
to create Netty Camel Routes directly from the hardware Endpoint, i.e. port.


== instructions for running

After successful compilation please go to the jeets-protocols-traccar main directory
to run the Traccar light GTS with your own configuration file

[source,text]
----
 java -jar target\jeets-protocols-traccar-x.y-jar-with-dependencies.jar setup\traccar.xml
----

and you can send messages to the protocols and associated ports defined in your xml file.

To observe the complete process you can proceed to the 
link:../../jeets-itests/device2protocols-traccar/README.adoc[device2protocols integration test].
