package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** Blocks generated by hbm2java */
@Entity
@Table(name = "blocks", schema = "public")
public class Blocks implements java.io.Serializable {

  private int id;
  private Integer sequence;
  private String blockId;
  private String serviceId;
  private String tripId;
  private String prevTripId;
  private String nextTripId;
  private String startStopId;
  private String endStopId;

  public Blocks() {}

  public Blocks(
      int id,
      String blockId,
      String serviceId,
      String tripId,
      String startStopId,
      String endStopId) {
    this.id = id;
    this.blockId = blockId;
    this.serviceId = serviceId;
    this.tripId = tripId;
    this.startStopId = startStopId;
    this.endStopId = endStopId;
  }

  public Blocks(
      int id,
      Integer sequence,
      String blockId,
      String serviceId,
      String tripId,
      String prevTripId,
      String nextTripId,
      String startStopId,
      String endStopId) {
    this.id = id;
    this.sequence = sequence;
    this.blockId = blockId;
    this.serviceId = serviceId;
    this.tripId = tripId;
    this.prevTripId = prevTripId;
    this.nextTripId = nextTripId;
    this.startStopId = startStopId;
    this.endStopId = endStopId;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  @Column(name = "sequence")
  public Integer getSequence() {
    return this.sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  @Column(name = "block_id", nullable = false)
  public String getBlockId() {
    return this.blockId;
  }

  public void setBlockId(String blockId) {
    this.blockId = blockId;
  }

  @Column(name = "service_id", nullable = false)
  public String getServiceId() {
    return this.serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  @Column(name = "trip_id", nullable = false)
  public String getTripId() {
    return this.tripId;
  }

  public void setTripId(String tripId) {
    this.tripId = tripId;
  }

  @Column(name = "prev_trip_id")
  public String getPrevTripId() {
    return this.prevTripId;
  }

  public void setPrevTripId(String prevTripId) {
    this.prevTripId = prevTripId;
  }

  @Column(name = "next_trip_id")
  public String getNextTripId() {
    return this.nextTripId;
  }

  public void setNextTripId(String nextTripId) {
    this.nextTripId = nextTripId;
  }

  @Column(name = "start_stop_id", nullable = false)
  public String getStartStopId() {
    return this.startStopId;
  }

  public void setStartStopId(String startStopId) {
    this.startStopId = startStopId;
  }

  @Column(name = "end_stop_id", nullable = false)
  public String getEndStopId() {
    return this.endStopId;
  }

  public void setEndStopId(String endStopId) {
    this.endStopId = endStopId;
  }
}
