package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/** Calendar generated by hbm2java */
@Entity
@Table(name = "calendar", schema = "public")
public class Calendar implements java.io.Serializable {

  private String serviceId;
  private boolean monday;
  private boolean tuesday;
  private boolean wednesday;
  private boolean thursday;
  private boolean friday;
  private boolean saturday;
  private boolean sunday;
  private Date startDate;
  private Date endDate;
  private String serviceName;

  public Calendar() {}

  public Calendar(
      String serviceId,
      boolean monday,
      boolean tuesday,
      boolean wednesday,
      boolean thursday,
      boolean friday,
      boolean saturday,
      boolean sunday,
      Date startDate,
      Date endDate) {
    this.serviceId = serviceId;
    this.monday = monday;
    this.tuesday = tuesday;
    this.wednesday = wednesday;
    this.thursday = thursday;
    this.friday = friday;
    this.saturday = saturday;
    this.sunday = sunday;
    this.startDate = startDate;
    this.endDate = endDate;
  }

  public Calendar(
      String serviceId,
      boolean monday,
      boolean tuesday,
      boolean wednesday,
      boolean thursday,
      boolean friday,
      boolean saturday,
      boolean sunday,
      Date startDate,
      Date endDate,
      String serviceName) {
    this.serviceId = serviceId;
    this.monday = monday;
    this.tuesday = tuesday;
    this.wednesday = wednesday;
    this.thursday = thursday;
    this.friday = friday;
    this.saturday = saturday;
    this.sunday = sunday;
    this.startDate = startDate;
    this.endDate = endDate;
    this.serviceName = serviceName;
  }

  @Id
  @Column(name = "service_id", unique = true, nullable = false)
  public String getServiceId() {
    return this.serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  @Column(name = "monday", nullable = false)
  public boolean isMonday() {
    return this.monday;
  }

  public void setMonday(boolean monday) {
    this.monday = monday;
  }

  @Column(name = "tuesday", nullable = false)
  public boolean isTuesday() {
    return this.tuesday;
  }

  public void setTuesday(boolean tuesday) {
    this.tuesday = tuesday;
  }

  @Column(name = "wednesday", nullable = false)
  public boolean isWednesday() {
    return this.wednesday;
  }

  public void setWednesday(boolean wednesday) {
    this.wednesday = wednesday;
  }

  @Column(name = "thursday", nullable = false)
  public boolean isThursday() {
    return this.thursday;
  }

  public void setThursday(boolean thursday) {
    this.thursday = thursday;
  }

  @Column(name = "friday", nullable = false)
  public boolean isFriday() {
    return this.friday;
  }

  public void setFriday(boolean friday) {
    this.friday = friday;
  }

  @Column(name = "saturday", nullable = false)
  public boolean isSaturday() {
    return this.saturday;
  }

  public void setSaturday(boolean saturday) {
    this.saturday = saturday;
  }

  @Column(name = "sunday", nullable = false)
  public boolean isSunday() {
    return this.sunday;
  }

  public void setSunday(boolean sunday) {
    this.sunday = sunday;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "start_date", nullable = false, length = 13)
  public Date getStartDate() {
    return this.startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "end_date", nullable = false, length = 13)
  public Date getEndDate() {
    return this.endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  @Column(name = "service_name")
  public String getServiceName() {
    return this.serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }
}
