package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CalendarDates generated by hbm2java
 */
@Entity
@Table(name = "calendar_dates", schema = "public")
public class CalendarDates implements java.io.Serializable {

    private CalendarDatesId id;
    private int exceptionType;

    public CalendarDates() {
    }

    public CalendarDates(CalendarDatesId id, int exceptionType) {
        this.id = id;
        this.exceptionType = exceptionType;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "serviceId", column = @Column(name = "service_id", nullable = false)),
            @AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 13)) })
    public CalendarDatesId getId() {
        return this.id;
    }

    public void setId(CalendarDatesId id) {
        this.id = id;
    }

    @Column(name = "exception_type", nullable = false)
    public int getExceptionType() {
        return this.exceptionType;
    }

    public void setExceptionType(int exceptionType) {
        this.exceptionType = exceptionType;
    }

}
