package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/** Frequencies generated by hbm2java */
@Entity
@Table(name = "frequencies", schema = "public")
public class Frequencies implements java.io.Serializable {

  private FrequenciesId id;
  private String endTime;
  private Integer headwaySecs;
  private Integer exactTimes;

  public Frequencies() {}

  public Frequencies(FrequenciesId id) {
    this.id = id;
  }

  public Frequencies(FrequenciesId id, String endTime, Integer headwaySecs, Integer exactTimes) {
    this.id = id;
    this.endTime = endTime;
    this.headwaySecs = headwaySecs;
    this.exactTimes = exactTimes;
  }

  @EmbeddedId
  @AttributeOverrides({
    @AttributeOverride(name = "tripId", column = @Column(name = "trip_id", nullable = false)),
    @AttributeOverride(
        name = "startTime",
        column = @Column(name = "start_time", nullable = false, length = 8))
  })
  public FrequenciesId getId() {
    return this.id;
  }

  public void setId(FrequenciesId id) {
    this.id = id;
  }

  @Column(name = "end_time", length = 8)
  public String getEndTime() {
    return this.endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  @Column(name = "headway_secs")
  public Integer getHeadwaySecs() {
    return this.headwaySecs;
  }

  public void setHeadwaySecs(Integer headwaySecs) {
    this.headwaySecs = headwaySecs;
  }

  @Column(name = "exact_times")
  public Integer getExactTimes() {
    return this.exactTimes;
  }

  public void setExactTimes(Integer exactTimes) {
    this.exactTimes = exactTimes;
  }
}
