package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/** FromStationsId generated by hbm2java */
@Embeddable
public class FromStationsId implements java.io.Serializable {

  private String stopId;
  private String stopCode;
  private String stopName;
  private String stopDesc;
  private BigDecimal stopLat;
  private BigDecimal stopLon;
  private String zoneId;
  private String stopUrl;
  private Integer locationType;
  private String parentStation;
  private String stopTimezone;
  private Integer wheelchairBoarding;
  private String platformCode;
  private String direction;
  private String position;
  private Serializable geom;

  public FromStationsId() {}

  public FromStationsId(
      String stopId,
      String stopCode,
      String stopName,
      String stopDesc,
      BigDecimal stopLat,
      BigDecimal stopLon,
      String zoneId,
      String stopUrl,
      Integer locationType,
      String parentStation,
      String stopTimezone,
      Integer wheelchairBoarding,
      String platformCode,
      String direction,
      String position,
      Serializable geom) {
    this.stopId = stopId;
    this.stopCode = stopCode;
    this.stopName = stopName;
    this.stopDesc = stopDesc;
    this.stopLat = stopLat;
    this.stopLon = stopLon;
    this.zoneId = zoneId;
    this.stopUrl = stopUrl;
    this.locationType = locationType;
    this.parentStation = parentStation;
    this.stopTimezone = stopTimezone;
    this.wheelchairBoarding = wheelchairBoarding;
    this.platformCode = platformCode;
    this.direction = direction;
    this.position = position;
    this.geom = geom;
  }

  @Column(name = "stop_id")
  public String getStopId() {
    return this.stopId;
  }

  public void setStopId(String stopId) {
    this.stopId = stopId;
  }

  @Column(name = "stop_code", length = 50)
  public String getStopCode() {
    return this.stopCode;
  }

  public void setStopCode(String stopCode) {
    this.stopCode = stopCode;
  }

  @Column(name = "stop_name")
  public String getStopName() {
    return this.stopName;
  }

  public void setStopName(String stopName) {
    this.stopName = stopName;
  }

  @Column(name = "stop_desc")
  public String getStopDesc() {
    return this.stopDesc;
  }

  public void setStopDesc(String stopDesc) {
    this.stopDesc = stopDesc;
  }

  @Column(name = "stop_lat", precision = 12, scale = 9)
  public BigDecimal getStopLat() {
    return this.stopLat;
  }

  public void setStopLat(BigDecimal stopLat) {
    this.stopLat = stopLat;
  }

  @Column(name = "stop_lon", precision = 12, scale = 9)
  public BigDecimal getStopLon() {
    return this.stopLon;
  }

  public void setStopLon(BigDecimal stopLon) {
    this.stopLon = stopLon;
  }

  @Column(name = "zone_id", length = 50)
  public String getZoneId() {
    return this.zoneId;
  }

  public void setZoneId(String zoneId) {
    this.zoneId = zoneId;
  }

  @Column(name = "stop_url")
  public String getStopUrl() {
    return this.stopUrl;
  }

  public void setStopUrl(String stopUrl) {
    this.stopUrl = stopUrl;
  }

  @Column(name = "location_type")
  public Integer getLocationType() {
    return this.locationType;
  }

  public void setLocationType(Integer locationType) {
    this.locationType = locationType;
  }

  @Column(name = "parent_station")
  public String getParentStation() {
    return this.parentStation;
  }

  public void setParentStation(String parentStation) {
    this.parentStation = parentStation;
  }

  @Column(name = "stop_timezone", length = 50)
  public String getStopTimezone() {
    return this.stopTimezone;
  }

  public void setStopTimezone(String stopTimezone) {
    this.stopTimezone = stopTimezone;
  }

  @Column(name = "wheelchair_boarding")
  public Integer getWheelchairBoarding() {
    return this.wheelchairBoarding;
  }

  public void setWheelchairBoarding(Integer wheelchairBoarding) {
    this.wheelchairBoarding = wheelchairBoarding;
  }

  @Column(name = "platform_code", length = 50)
  public String getPlatformCode() {
    return this.platformCode;
  }

  public void setPlatformCode(String platformCode) {
    this.platformCode = platformCode;
  }

  @Column(name = "direction", length = 50)
  public String getDirection() {
    return this.direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  @Column(name = "position", length = 50)
  public String getPosition() {
    return this.position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  @Column(name = "geom")
  public Serializable getGeom() {
    return this.geom;
  }

  public void setGeom(Serializable geom) {
    this.geom = geom;
  }

  public boolean equals(Object other) {
    if ((this == other)) return true;
    if ((other == null)) return false;
    if (!(other instanceof FromStationsId)) return false;
    FromStationsId castOther = (FromStationsId) other;

    return ((this.getStopId() == castOther.getStopId())
            || (this.getStopId() != null
                && castOther.getStopId() != null
                && this.getStopId().equals(castOther.getStopId())))
        && ((this.getStopCode() == castOther.getStopCode())
            || (this.getStopCode() != null
                && castOther.getStopCode() != null
                && this.getStopCode().equals(castOther.getStopCode())))
        && ((this.getStopName() == castOther.getStopName())
            || (this.getStopName() != null
                && castOther.getStopName() != null
                && this.getStopName().equals(castOther.getStopName())))
        && ((this.getStopDesc() == castOther.getStopDesc())
            || (this.getStopDesc() != null
                && castOther.getStopDesc() != null
                && this.getStopDesc().equals(castOther.getStopDesc())))
        && ((this.getStopLat() == castOther.getStopLat())
            || (this.getStopLat() != null
                && castOther.getStopLat() != null
                && this.getStopLat().equals(castOther.getStopLat())))
        && ((this.getStopLon() == castOther.getStopLon())
            || (this.getStopLon() != null
                && castOther.getStopLon() != null
                && this.getStopLon().equals(castOther.getStopLon())))
        && ((this.getZoneId() == castOther.getZoneId())
            || (this.getZoneId() != null
                && castOther.getZoneId() != null
                && this.getZoneId().equals(castOther.getZoneId())))
        && ((this.getStopUrl() == castOther.getStopUrl())
            || (this.getStopUrl() != null
                && castOther.getStopUrl() != null
                && this.getStopUrl().equals(castOther.getStopUrl())))
        && ((this.getLocationType() == castOther.getLocationType())
            || (this.getLocationType() != null
                && castOther.getLocationType() != null
                && this.getLocationType().equals(castOther.getLocationType())))
        && ((this.getParentStation() == castOther.getParentStation())
            || (this.getParentStation() != null
                && castOther.getParentStation() != null
                && this.getParentStation().equals(castOther.getParentStation())))
        && ((this.getStopTimezone() == castOther.getStopTimezone())
            || (this.getStopTimezone() != null
                && castOther.getStopTimezone() != null
                && this.getStopTimezone().equals(castOther.getStopTimezone())))
        && ((this.getWheelchairBoarding() == castOther.getWheelchairBoarding())
            || (this.getWheelchairBoarding() != null
                && castOther.getWheelchairBoarding() != null
                && this.getWheelchairBoarding().equals(castOther.getWheelchairBoarding())))
        && ((this.getPlatformCode() == castOther.getPlatformCode())
            || (this.getPlatformCode() != null
                && castOther.getPlatformCode() != null
                && this.getPlatformCode().equals(castOther.getPlatformCode())))
        && ((this.getDirection() == castOther.getDirection())
            || (this.getDirection() != null
                && castOther.getDirection() != null
                && this.getDirection().equals(castOther.getDirection())))
        && ((this.getPosition() == castOther.getPosition())
            || (this.getPosition() != null
                && castOther.getPosition() != null
                && this.getPosition().equals(castOther.getPosition())))
        && ((this.getGeom() == castOther.getGeom())
            || (this.getGeom() != null
                && castOther.getGeom() != null
                && this.getGeom().equals(castOther.getGeom())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getStopId() == null ? 0 : this.getStopId().hashCode());
    result = 37 * result + (getStopCode() == null ? 0 : this.getStopCode().hashCode());
    result = 37 * result + (getStopName() == null ? 0 : this.getStopName().hashCode());
    result = 37 * result + (getStopDesc() == null ? 0 : this.getStopDesc().hashCode());
    result = 37 * result + (getStopLat() == null ? 0 : this.getStopLat().hashCode());
    result = 37 * result + (getStopLon() == null ? 0 : this.getStopLon().hashCode());
    result = 37 * result + (getZoneId() == null ? 0 : this.getZoneId().hashCode());
    result = 37 * result + (getStopUrl() == null ? 0 : this.getStopUrl().hashCode());
    result = 37 * result + (getLocationType() == null ? 0 : this.getLocationType().hashCode());
    result = 37 * result + (getParentStation() == null ? 0 : this.getParentStation().hashCode());
    result = 37 * result + (getStopTimezone() == null ? 0 : this.getStopTimezone().hashCode());
    result =
        37 * result
            + (getWheelchairBoarding() == null ? 0 : this.getWheelchairBoarding().hashCode());
    result = 37 * result + (getPlatformCode() == null ? 0 : this.getPlatformCode().hashCode());
    result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
    result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
    result = 37 * result + (getGeom() == null ? 0 : this.getGeom().hashCode());
    return result;
  }
}
