package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/** RouteStops generated by hbm2java */
@Entity
@Table(name = "route_stops", schema = "public")
public class RouteStops implements java.io.Serializable {

  private RouteStopsId id;
  private int order;
  private Date startDate;
  private Date endDate;

  public RouteStops() {}

  public RouteStops(RouteStopsId id, int order, Date startDate, Date endDate) {
    this.id = id;
    this.order = order;
    this.startDate = startDate;
    this.endDate = endDate;
  }

  @EmbeddedId
  @AttributeOverrides({
    @AttributeOverride(name = "routeId", column = @Column(name = "route_id", nullable = false)),
    @AttributeOverride(
        name = "directionId",
        column = @Column(name = "direction_id", nullable = false)),
    @AttributeOverride(name = "stopId", column = @Column(name = "stop_id", nullable = false))
  })
  public RouteStopsId getId() {
    return this.id;
  }

  public void setId(RouteStopsId id) {
    this.id = id;
  }

  @Column(name = "order", nullable = false)
  public int getOrder() {
    return this.order;
  }

  public void setOrder(int order) {
    this.order = order;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "start_date", nullable = false, length = 13)
  public Date getStartDate() {
    return this.startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "end_date", nullable = false, length = 13)
  public Date getEndDate() {
    return this.endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }
}
