package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/** RouteStopsId generated by hbm2java */
@Embeddable
public class RouteStopsId implements java.io.Serializable {

  private String routeId;
  private int directionId;
  private String stopId;

  public RouteStopsId() {}

  public RouteStopsId(String routeId, int directionId, String stopId) {
    this.routeId = routeId;
    this.directionId = directionId;
    this.stopId = stopId;
  }

  @Column(name = "route_id", nullable = false)
  public String getRouteId() {
    return this.routeId;
  }

  public void setRouteId(String routeId) {
    this.routeId = routeId;
  }

  @Column(name = "direction_id", nullable = false)
  public int getDirectionId() {
    return this.directionId;
  }

  public void setDirectionId(int directionId) {
    this.directionId = directionId;
  }

  @Column(name = "stop_id", nullable = false)
  public String getStopId() {
    return this.stopId;
  }

  public void setStopId(String stopId) {
    this.stopId = stopId;
  }

  public boolean equals(Object other) {
    if ((this == other)) return true;
    if ((other == null)) return false;
    if (!(other instanceof RouteStopsId)) return false;
    RouteStopsId castOther = (RouteStopsId) other;

    return ((this.getRouteId() == castOther.getRouteId())
            || (this.getRouteId() != null
                && castOther.getRouteId() != null
                && this.getRouteId().equals(castOther.getRouteId())))
        && (this.getDirectionId() == castOther.getDirectionId())
        && ((this.getStopId() == castOther.getStopId())
            || (this.getStopId() != null
                && castOther.getStopId() != null
                && this.getStopId().equals(castOther.getStopId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getRouteId() == null ? 0 : this.getRouteId().hashCode());
    result = 37 * result + this.getDirectionId();
    result = 37 * result + (getStopId() == null ? 0 : this.getStopId().hashCode());
    return result;
  }
}
