package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** Routes generated by hbm2java */
@Entity
@Table(name = "routes", schema = "public")
public class Routes implements java.io.Serializable {

  private String routeId;
  private String agencyId;
  private String routeShortName;
  private String routeLongName;
  private String routeDesc;
  private int routeType;
  private String routeUrl;
  private String routeColor;
  private String routeTextColor;
  private Integer routeSortOrder;
  private Integer minHeadwayMinutes;
  private Serializable geom;

  public Routes() {}

  public Routes(String routeId, int routeType) {
    this.routeId = routeId;
    this.routeType = routeType;
  }

  public Routes(
      String routeId,
      String agencyId,
      String routeShortName,
      String routeLongName,
      String routeDesc,
      int routeType,
      String routeUrl,
      String routeColor,
      String routeTextColor,
      Integer routeSortOrder,
      Integer minHeadwayMinutes,
      Serializable geom) {
    this.routeId = routeId;
    this.agencyId = agencyId;
    this.routeShortName = routeShortName;
    this.routeLongName = routeLongName;
    this.routeDesc = routeDesc;
    this.routeType = routeType;
    this.routeUrl = routeUrl;
    this.routeColor = routeColor;
    this.routeTextColor = routeTextColor;
    this.routeSortOrder = routeSortOrder;
    this.minHeadwayMinutes = minHeadwayMinutes;
    this.geom = geom;
  }

  @Id
  @Column(name = "route_id", unique = true, nullable = false)
  public String getRouteId() {
    return this.routeId;
  }

  public void setRouteId(String routeId) {
    this.routeId = routeId;
  }

  @Column(name = "agency_id")
  public String getAgencyId() {
    return this.agencyId;
  }

  public void setAgencyId(String agencyId) {
    this.agencyId = agencyId;
  }

  @Column(name = "route_short_name")
  public String getRouteShortName() {
    return this.routeShortName;
  }

  public void setRouteShortName(String routeShortName) {
    this.routeShortName = routeShortName;
  }

  @Column(name = "route_long_name")
  public String getRouteLongName() {
    return this.routeLongName;
  }

  public void setRouteLongName(String routeLongName) {
    this.routeLongName = routeLongName;
  }

  @Column(name = "route_desc", length = 1023)
  public String getRouteDesc() {
    return this.routeDesc;
  }

  public void setRouteDesc(String routeDesc) {
    this.routeDesc = routeDesc;
  }

  @Column(name = "route_type", nullable = false)
  public int getRouteType() {
    return this.routeType;
  }

  public void setRouteType(int routeType) {
    this.routeType = routeType;
  }

  @Column(name = "route_url")
  public String getRouteUrl() {
    return this.routeUrl;
  }

  public void setRouteUrl(String routeUrl) {
    this.routeUrl = routeUrl;
  }

  @Column(name = "route_color", length = 6)
  public String getRouteColor() {
    return this.routeColor;
  }

  public void setRouteColor(String routeColor) {
    this.routeColor = routeColor;
  }

  @Column(name = "route_text_color", length = 6)
  public String getRouteTextColor() {
    return this.routeTextColor;
  }

  public void setRouteTextColor(String routeTextColor) {
    this.routeTextColor = routeTextColor;
  }

  @Column(name = "route_sort_order")
  public Integer getRouteSortOrder() {
    return this.routeSortOrder;
  }

  public void setRouteSortOrder(Integer routeSortOrder) {
    this.routeSortOrder = routeSortOrder;
  }

  @Column(name = "min_headway_minutes")
  public Integer getMinHeadwayMinutes() {
    return this.minHeadwayMinutes;
  }

  public void setMinHeadwayMinutes(Integer minHeadwayMinutes) {
    this.minHeadwayMinutes = minHeadwayMinutes;
  }

  @Column(name = "geom")
  public Serializable getGeom() {
    return this.geom;
  }

  public void setGeom(Serializable geom) {
    this.geom = geom;
  }
}
