package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** RouteFilters generated by hbm2java */
@Entity
@Table(name = "route_filters", schema = "public")
public class RouteFilters implements java.io.Serializable {

  private String routeId;
  private String agencyId;
  private String description;

  public RouteFilters() {}

  public RouteFilters(String routeId) {
    this.routeId = routeId;
  }

  public RouteFilters(String routeId, String agencyId, String description) {
    this.routeId = routeId;
    this.agencyId = agencyId;
    this.description = description;
  }

  @Id
  @Column(name = "route_id", unique = true, nullable = false)
  public String getRouteId() {
    return this.routeId;
  }

  public void setRouteId(String routeId) {
    this.routeId = routeId;
  }

  @Column(name = "agency_id")
  public String getAgencyId() {
    return this.agencyId;
  }

  public void setAgencyId(String agencyId) {
    this.agencyId = agencyId;
  }

  @Column(name = "description")
  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }
}
