package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** RouteType generated by hbm2java */
@Entity
@Table(name = "route_type", schema = "public")
public class RouteType implements java.io.Serializable {

  private int routeType;
  private String routeTypeName;
  private String routeTypeDesc;

  public RouteType() {}

  public RouteType(int routeType) {
    this.routeType = routeType;
  }

  public RouteType(int routeType, String routeTypeName, String routeTypeDesc) {
    this.routeType = routeType;
    this.routeTypeName = routeTypeName;
    this.routeTypeDesc = routeTypeDesc;
  }

  @Id
  @Column(name = "route_type", unique = true, nullable = false)
  public int getRouteType() {
    return this.routeType;
  }

  public void setRouteType(int routeType) {
    this.routeType = routeType;
  }

  @Column(name = "route_type_name")
  public String getRouteTypeName() {
    return this.routeTypeName;
  }

  public void setRouteTypeName(String routeTypeName) {
    this.routeTypeName = routeTypeName;
  }

  @Column(name = "route_type_desc", length = 1023)
  public String getRouteTypeDesc() {
    return this.routeTypeDesc;
  }

  public void setRouteTypeDesc(String routeTypeDesc) {
    this.routeTypeDesc = routeTypeDesc;
  }
}
