package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/** StopTimes generated by hbm2java */
@Entity
@Table(name = "stop_times", schema = "public")
public class StopTimes implements java.io.Serializable {

  private StopTimesId id;
  private String stopId;
  private String arrivalTime;
  private String departureTime;
  private String stopHeadsign;
  private Integer pickupType;
  private Integer dropOffType;
  private BigDecimal shapeDistTraveled;
  private Boolean timepoint;

  public StopTimes() {}

  public StopTimes(StopTimesId id, String stopId) {
    this.id = id;
    this.stopId = stopId;
  }

  public StopTimes(
      StopTimesId id,
      String stopId,
      String arrivalTime,
      String departureTime,
      String stopHeadsign,
      Integer pickupType,
      Integer dropOffType,
      BigDecimal shapeDistTraveled,
      Boolean timepoint) {
    this.id = id;
    this.stopId = stopId;
    this.arrivalTime = arrivalTime;
    this.departureTime = departureTime;
    this.stopHeadsign = stopHeadsign;
    this.pickupType = pickupType;
    this.dropOffType = dropOffType;
    this.shapeDistTraveled = shapeDistTraveled;
    this.timepoint = timepoint;
  }

  @EmbeddedId
  @AttributeOverrides({
    @AttributeOverride(name = "tripId", column = @Column(name = "trip_id", nullable = false)),
    @AttributeOverride(
        name = "stopSequence",
        column = @Column(name = "stop_sequence", nullable = false))
  })
  public StopTimesId getId() {
    return this.id;
  }

  public void setId(StopTimesId id) {
    this.id = id;
  }

  @Column(name = "stop_id", nullable = false)
  public String getStopId() {
    return this.stopId;
  }

  public void setStopId(String stopId) {
    this.stopId = stopId;
  }

  @Column(name = "arrival_time", length = 9)
  public String getArrivalTime() {
    return this.arrivalTime;
  }

  public void setArrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
  }

  @Column(name = "departure_time", length = 9)
  public String getDepartureTime() {
    return this.departureTime;
  }

  public void setDepartureTime(String departureTime) {
    this.departureTime = departureTime;
  }

  @Column(name = "stop_headsign")
  public String getStopHeadsign() {
    return this.stopHeadsign;
  }

  public void setStopHeadsign(String stopHeadsign) {
    this.stopHeadsign = stopHeadsign;
  }

  @Column(name = "pickup_type")
  public Integer getPickupType() {
    return this.pickupType;
  }

  public void setPickupType(Integer pickupType) {
    this.pickupType = pickupType;
  }

  @Column(name = "drop_off_type")
  public Integer getDropOffType() {
    return this.dropOffType;
  }

  public void setDropOffType(Integer dropOffType) {
    this.dropOffType = dropOffType;
  }

  @Column(name = "shape_dist_traveled", precision = 20, scale = 10)
  public BigDecimal getShapeDistTraveled() {
    return this.shapeDistTraveled;
  }

  public void setShapeDistTraveled(BigDecimal shapeDistTraveled) {
    this.shapeDistTraveled = shapeDistTraveled;
  }

  @Column(name = "timepoint")
  public Boolean getTimepoint() {
    return this.timepoint;
  }

  public void setTimepoint(Boolean timepoint) {
    this.timepoint = timepoint;
  }
}
