package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ToStations generated by hbm2java
 */
@Entity
@Table(name = "to_stations", schema = "public")
public class ToStations implements java.io.Serializable {

    private ToStationsId id;

    public ToStations() {
    }

    public ToStations(ToStationsId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "stopId", column = @Column(name = "stop_id")),
            @AttributeOverride(name = "stopCode", column = @Column(name = "stop_code", length = 50)),
            @AttributeOverride(name = "stopName", column = @Column(name = "stop_name")),
            @AttributeOverride(name = "stopDesc", column = @Column(name = "stop_desc")),
            @AttributeOverride(name = "stopLat", column = @Column(name = "stop_lat", precision = 12, scale = 9)),
            @AttributeOverride(name = "stopLon", column = @Column(name = "stop_lon", precision = 12, scale = 9)),
            @AttributeOverride(name = "zoneId", column = @Column(name = "zone_id", length = 50)),
            @AttributeOverride(name = "stopUrl", column = @Column(name = "stop_url")),
            @AttributeOverride(name = "locationType", column = @Column(name = "location_type")),
            @AttributeOverride(name = "parentStation", column = @Column(name = "parent_station")),
            @AttributeOverride(name = "stopTimezone", column = @Column(name = "stop_timezone", length = 50)),
            @AttributeOverride(name = "wheelchairBoarding", column = @Column(name = "wheelchair_boarding")),
            @AttributeOverride(name = "platformCode", column = @Column(name = "platform_code", length = 50)),
            @AttributeOverride(name = "direction", column = @Column(name = "direction", length = 50)),
            @AttributeOverride(name = "position", column = @Column(name = "position", length = 50)),
            @AttributeOverride(name = "geom", column = @Column(name = "geom")) })
    public ToStationsId getId() {
        return this.id;
    }

    public void setId(ToStationsId id) {
        this.id = id;
    }

}
