package org.jeets.model.gtfs;
// Generated 08.11.2017 22:44:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** Transfers generated by hbm2java */
@Entity
@Table(name = "transfers", schema = "public")
public class Transfers implements java.io.Serializable {

  private int id;
  private String fromStopId;
  private String toStopId;
  private Integer transferType;
  private Integer minTransferTime;

  public Transfers() {}

  public Transfers(int id) {
    this.id = id;
  }

  public Transfers(
      int id, String fromStopId, String toStopId, Integer transferType, Integer minTransferTime) {
    this.id = id;
    this.fromStopId = fromStopId;
    this.toStopId = toStopId;
    this.transferType = transferType;
    this.minTransferTime = minTransferTime;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  @Column(name = "from_stop_id")
  public String getFromStopId() {
    return this.fromStopId;
  }

  public void setFromStopId(String fromStopId) {
    this.fromStopId = fromStopId;
  }

  @Column(name = "to_stop_id")
  public String getToStopId() {
    return this.toStopId;
  }

  public void setToStopId(String toStopId) {
    this.toStopId = toStopId;
  }

  @Column(name = "transfer_type")
  public Integer getTransferType() {
    return this.transferType;
  }

  public void setTransferType(Integer transferType) {
    this.transferType = transferType;
  }

  @Column(name = "min_transfer_time")
  public Integer getMinTransferTime() {
    return this.minTransferTime;
  }

  public void setMinTransferTime(Integer minTransferTime) {
    this.minTransferTime = minTransferTime;
  }
}
